### ISSUE TITLE
questions about "session" vs. "database" in settings

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#105]
What is the difference between "session" and database in "current bot" in config, and what use the information to "bot personality" and how I filled out this form

**Comment by Dave-Morton** [comment]
@Amjed1991 It's probably a good idea to just give a short title to your issue posts, and putting the question in the body of the post itself. I'll fix it this time, but please be mindful of this in the future.

Ok, now to the questions. First off, the setting in the config that you referred to is actually a throwback from an earlier version that used to give the option to store the chatbot's  config in a database table, instead of the PHP session variable. this option proved more trouble than it was worth, but the option never got removed from the install script (It's simply ignored, ATM). It will get removed at some point, but I can't do it right now, due to time pressures with work and school.

As for the bot personality, this is a collection of "personality traits" for the chatbot. Things like favorite color, authors, celebrities and such are stored in the database, based on entries you put in on the bot's admin page. The form itself SHOULD be self explanatory, but if you're having trouble with it, please describe your problem with it, and I'll try to help you get it figured out.

**Comment by Amjed1991** [comment]
Thank you , that's ok
