### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by BeZazz** [Program-O/Program-O#107]
I noticed before the forum was down.

If you would like me to host it or a mirror of it let me know.
(Have ran a hosting biz for 10 years, was a partner in one before that)

**Comment by Dave-Morton** [comment]
Since I've been tied up with family, school and other things of a personal nature, Liz has stepped back into the leadership role, and has decided to archive the forum, move to a wiki for "knowledge base" type support, and (of course) maintain the GitHub site. The forum being down is only temporary, but will only ever come back as an archive. Any support related questions or issues that can't be handled via the wiki can be asked here as an issue, and we'll do our best to help fix things. We do appreciate the offer, but it's not a matter of hosting at this point.
