### ISSUE TITLE
https

### ISSUE THREAD

**Issue by BeZazz** [Program-O/Program-O#113]
I was wondering with the likes of Let's Encrypt.
More and more sites are going the route of using SSL.

Currently to use https I have a few issues such as Search/Edit AIML which has http://yui.yahooapis.com/3.18.0/build/yui/yui-min.js
(maybe this could be stored locally)

Would it be possible to make Program-O more https friendly?

**Comment by Dave-Morton** [comment]
I was looking into seeing if there is a "protocol-agnostic" way to load the YUI library from Yahoo, but it seems that they don't have an SSL version of the script (or, they DO, but they let the cert expire for it). I **STILL** want to port this part of the admin over to use jQuery, but I simply haven't had the time to work on it. Please feel free to modify the code to allow for local use, for now, and I'll try to bump up the priority for addressing this.

**Comment by BeZazz** [comment]
Ok,
Thanks :)

**Comment by BeZazz** [comment]
Just an update I downloaded http://yui.yahooapis.com/3.18.0/build/yui/yui-min.js to the server an linked to scripts/yui-min.js

Still had issues, it turns out that js file has 13/14 links to http sites.

As it is 4am here I gave up and added an exception in the browser. lol

**Comment by Dave-Morton** [comment]
Well, that's not good. I'm definitely moving up the priority of this issue to switch over to a jQuery solution. I still won't be able to do much till next weekend, but it will be the next thing I work on.

**Comment by RamboVital** [comment]
I am having the same problem with my https website.  Here is my error I got from Search/Edit AIML.

Mixed Content: The page at 'https://getb08.com/admin/index.php?page=editAiml' was loaded over HTTPS, but requested an insecure script 'http://yui.yahooapis.com/3.18.0/build/yui/yui-min.js'. This request has been blocked; the content must be served over HTTPS.

Is there way of fixing is problem?

Thank you for your time.  Cheers.

**Comment by RamboVital** [comment]
I fixed the problem!  

Ok, here I go.....

1)  Download http://yui.zenfs.com/releases/yui3/yui_3.18.0.zip from https://github.com/yui/yui3/releases/tag/v3.18.0
2)  Upload it to your website.  (I put it in my program O admin directory) (https://*/admin/yui)
3)  Edit your default.page.htm in your admin directory.
4)  Find the line (http://yui.yahooapis.com/3.18.0/build/yui/yui-min.js)
5)  Change it to (https://[Your URL]/admin/yui/build/yui/yui-min.js)   Mine looks like this. (https://*/admin/yui/build/yui/yui-min.js)

Note: That I just uploaded the whole thing.  It's very likely I didn't need to do that at all but, I just did it so I didn't have to worry about possible problems or mistakes.  Also, if you are wondering why are there so many files is because the default.page.htm asks for yui-min.js external.  Which ask for a for a combo of files.  Which likely needs other files to work correctly.  yui-min.js is nothing more then a tip of an iceberg of external files.  If there is any other external files that Program O needs please let me know.

I hope this helps everyone here.  Cheers!

**Comment by Dave-Morton** [comment]
I really didn't want to "fix" this until I had found a suitable way to replace YUI with a jQuery solution, but given the number of individuals who reported this issue (both here, and via other means), I decided to address it bu replacing the remote (http) reference to YUI with a local one. The most recent commit in the DEV branch now has a local reference to YUI included.

**Comment by Dave-Morton** [comment]
BTW, @RamboVital -  thanks for outlining how to do that DIY fix. It's not the way I would have done it, but if it works, who's to judge?

**Comment by Dave-Morton** [comment]
Before I close this issue, is anyone still having trouble with this?

**Comment by Program-O** [comment]
closing as no response for 30 days
