### ISSUE TITLE
Foreign language in <THAT>

### ISSUE THREAD

**Issue by Eroleice** [Program-O/Program-O#114]
Thanks for the work and I really love it!

I tried to put Chinese characters in THAT tag, it doesn't work.

I've tested with English, and it works fine.

Is there anything I can do?

**Comment by Dave-Morton** [comment]
Can you give an example of the Chinese text that you've placed into a <that> tag? this will help us to determine where the problem lies. Thanks.

**Comment by Eroleice** [comment]
I put only 3 AIML there. The first one is the start:

> User Input: 你好
> Bot response: 你好，请问你的名字是？

Second:

> THAT: 请问你的名字是
> User Input: 测试
> Bot response: 测试成功

Third:

> THAT:你好，请问你的名字是？
> User Input: 测试
> Bot response: 测试成功

So when I get the response from bot at the beginning, I type "测试", and I get blink back. I thought the Chinese punctuation might be the problem. But after I change the first Bot response into "请问你的名字是", which is exactly same `<that>` as second AIML, I still get blink from bot.

While I also notice that if the previous answer (in English) from bot has a punctuation, the bots can't recognize `<that>`, no matter that's a full sentece in `<that>` or part of it, is that normal?

**Comment by Dave-Morton** [comment]
@Eroleice - Out of curiosity, when you first reported this, was your Program O version up to date? I ask because a few days before you reported this issue, I had fixed another issue with the `<that>` tag that may well also apply to your situation. If it was, no worries; I'll continue to work on this. but if it was more than a few days since you've updated Program O, I may well be trying to find an issue that has already been fixed. Please let me know. Thanks.

**Comment by Program-O** [comment]
closing not response in 30 days

**Comment by zj2050** [comment]
@Eroleice 你好，我添加了一个中文词条， 但用中文提问的时候回复的还是英文，在数据库已经添加，请问要修改 哪儿吗？
谢谢
