### ISSUE TITLE
About bot personality

### ISSUE THREAD

**Issue by Amjed1991** [Program-O/Program-O#120]
When I met the bot personality form, and I test, the bot does not answer me, and other times even if I change the bot, it takes me information for this one

**Comment by Dave-Morton** [comment]
@Amjed1991 - That statement made very little sense. Could you please explain in more detail? Thanks.

**Comment by Amjed1991** [comment]
I filled out the form bot personality, now when I try, I get "age, name ..." or he does not answer me, or he meets me name another example of bot id .
In addition, the bot response time is a little long, I update several times to answer me

**Comment by Amjed1991** [comment]
When I said for the Bot : name or , age ... It return " No AIML category found. This is a Default Response. "

**Comment by Dave-Morton** [comment]
Ok, that sounds like you haven't yet added any AIML categories to your bot yet. If you have, then there's something else wrong, so I would need to have you provide a ZIP archive of all of the AIML files that you've uploaded to the chatbot so that I can test them, as well as any inputs that have returned that response from the bot.

**Comment by Amjed1991** [comment]
Yes thank you with a walking AIML file, but through the bot personality form, even after that I met, it does not take this info, it shows me

**Comment by Amjed1991** [comment]
Please I'm the bot takes me for example: my skills is limited "when I ask for something that is not how I

**Comment by Dave-Morton** [comment]
In order for me to help figure out what's going on, I need more specific information, and the best way to get this information is to be able to see what's going on directly. Please send me an email to dmorton@geekcavecreations.com so we can discuss how best to do this. The information that we need to discuss is best handled privately.

**Comment by Dave-Morton** [comment]
Ok, after a rather lengthy email conversation in French (via Google Translate, since I don't speak French) we were able to work out what the problem was. As it turns out, it was a bug in the AIML files being used, rather than a bug in Program O. The upshot was that the AIML categories being used had hard-coded responses, rather than using the `<get>` tag, so @Amjed1991 was getting unexpected responses. I gave a quick tutorial on how to access the bot's personality via the `<get>` tag, and all is good (I think and hope!). To anyone else who is struggling with this, I recommend following tutorials:

1.) (ALICE AIML Primer)[http://www.alicebot.org/documentation/aiml-primer.html]
2.) (AIML Tutorial-Basic AIML)[http://www.teamliquid.net/blogs/145297-aiml-tutorial-basic-aiml-how-to-write]
