### ISSUE TITLE
Tech bot function does not work

### ISSUE THREAD

**Issue by JohnnyLe** [Program-O/Program-O#123]
Hello team,

I create new Teach as bellow and it added success with the message "AIML added"

![image](https://cloud.githubusercontent.com/assets/1794584/14759004/a19429a0-093c-11e6-9377-ea5a6c2b96da.png)

But when I try in front-end, it does not show the answers 

![image](https://cloud.githubusercontent.com/assets/1794584/14759024/7503f75c-093d-11e6-9ba2-f2c31b4e5946.png)

Best regards
Johnny

**Comment by Dave-Morton** [comment]
Have you made sure that the bot's current topic is healthcare? Also, is your bot set up to generate debug files? If so, it would be helpful to see the contents of that file.

**Comment by JohnnyLe** [comment]
Hi Dave,

Thank you for the response. 
Could you please let me know where I can set current topic for the bot?

**Comment by Dave-Morton** [comment]
Tell the bot "I want to talk about healthcare".

That is, if you're using any of the dozens of "standard" AIML sets with your chatbot. If you aren't, then you can use the teaching interface to put that AIML category in. Just make sure that you also put in a "breakout" category that removes the topic. Otherwise, all your chatbot will want to talk about is healthcare. :D 
To get the chatbot to use the topic of healthcare (or any topic, for that matter), simply follow these steps:

1.) navigate the admin page to get to the teaching interface.
2.) Leave the topic and Previous Bot Response (THAT) fields blank.
3.) In the User Input field, put "LET US TALK ABOUT *" (minus the quotes, of course)
4.) In the Bot Response field, input the following AIML:

```XML
<think><set name="topic"><star/></set></think>
Ok, let's talk about <star/>.
```
5.) Hit the "Teach" button.

{Please note that this is not the only way that the response can or should be worded. The bot's output  (the 2nd line, above) can be worded any way you wish. Just make sure that the first line of AIML is there, and that it's entered as I typed it, until you master the subtlties and nuances of crafting AIML categories on your own.}

Now... To make a "Breakout" category, you would do something like this:

1.) Navigate the admin page to the teaching interface.
2.) Leave the THAT line blank, but put HEALTHCARE in the Topic field (or whatever topic wou want to break out from).
3.) In the User Input field, just put in a *
4.) In the Bot response, put in the following AIML code, followed by whatever response you want the bot to give:

```XML
<think><set name="topic"></set></think>
```
5.) hit the "Teach" button.

Please note that you will need a "breakout" category for EACH topic that you set. Topics are a powerful way to direct the conversation when used correctly, but things go south quickly if you don't take the time to make sure they're written properly.

**Comment by JohnnyLe** [comment]
Thank you Dave, I got it.
