### ISSUE TITLE
PHP Tags

### ISSUE THREAD

**Issue by Depicus** [Program-O/Program-O#124]
Is there anything special we need to do to enable php tags. I have define('USE_CUSTOM_TAGS', true); in the config but not getting any hits when I get a bot response on the php file ?

**Comment by Dave-Morton** [comment]
In order to answer this properly, I'd need to see how you're implementing the `<php>` tag in your AIML. Using the PHP tag isn't hard, but it's **VERY** dangerous, and potentially damaging (not to mention insecure) if not used correctly.

**Comment by Depicus** [comment]
This is the aiml, actions.php is in the chatbot folder and I just copied a function I use everywhere to test.

    <aiml version="1.0">
      <category>
    <pattern>HELLO *</pattern>
    <template>A grand hello to you</template>
      </category>
      <category>
    <pattern>WHERE ARE MY DOCS</pattern>
    <template>Do you have the policy number ?</template>
      </category>
      <category>
    <pattern>YES</pattern>
    <that>DO YOU HAVE THE POLICY NUMBER ?</that>
    <template>
      <?php include_once 'actions.php'; debugToEmail();?>
    </template>
      </category>
    </aiml>

**Comment by Dave-Morton** [comment]
Ok, great. The next question would be the location of actions.php, and whether there is anything showing up in the error logs regarding that file, such as any sort of "file not found" error. I'll incorporate that AIML into one of my test chatbots to see what sort of response I get, then I'll report back with any suggestions that come to mind.

**Comment by Dave-Morton** [comment]
oops? the function for parsing PHP tags has not yet been completed. That's going to be a problem if you want to do something with PHP. 

I'm currently in the final weeks of my spring semester in school, and as such don't have enough time right now to do more than answer simple support questions. I'll make a note to revisit this in June, when I'm out of school for a while.

**Comment by Depicus** [comment]
That's ok no problem - I can wait as it was just a proof of concept for the business so I'll just wing it on that part. I'll check back later to see how you are getting on - good luck and thanks for the support.

**Comment by Dave-Morton** [comment]
A quick question before you go...

Where do you have the file actions.php? In order for it to work with Program O, it needs to be in a place that the script can locate it. As you have it in the AIML, that would be in the custom_tags folder. If you have it elsewhere, you'll need to supply the proper path to the file, as well. Just a heads up. :)

**Comment by Depicus** [comment]
Cheers I'll have a look and move as I'm 99% sure it wasn't in custom_tags

**Comment by FullCustom** [comment]
I'm interested in this as well as I'd like to program by bot to help a customer fill out a php form.

**Comment by Dave-Morton** [comment]
A few years ago, when Liz and I were initially exploring the possibilities of using a custom tag to parse PHP commands, I developed a "quick & dirty" means of doing so through the use of PHP's `eval()` tag, but never went any further than a few simple tests. Since then, I've read a number of articles that all had the opinion that "`eval() === evil`". I'm sure that there are a number of ways to accomplish the task of executing PHP scripts from AIML, but it seems to me that whatever method is eventually used must end up being safer and more secure than `eval()`. I'll look into it further in a few weeks, once school is done for the summer.

**Comment by Depicus** [comment]
You could always sanity check by using the defined include file in a function_exists call i.e.

    <?php
    // first check to see if this is a built in function as we don't want to allow those
    if (function_exists('sendDebugEmail')) {
      print "sendDebugEmail exists so exit as it is unsafe as we did not define it";
    } else {
      include_once "filenamewewerepassed.php";
      eval("sendDebugEmail(anyparamsthatexisted)");
    } 

Not tried it but the theory sounds good.

**Comment by Dave-Morton** [comment]
@Depicus the native PHP call `function_exists()` will return true if 'sendDebugEmail' exists *whether it's a native PHP function or defined by a script*, so your sanity check wouldn't work the way you intend it. Also, if 'sendDebugEmail' did **NOT** exist, the call to `eval()` in your else block would through a fatal error because the function does *not* exist.

@FullCustom - I've looked a bit more into this, and came up with something that could be the start of something useful, though it would require some proper security/sanity checking. In the file chatbot/addons/custom_tags/custom_tags.php, in the function `parse_php_tag`, replace this line:

`$response_string = implode_recursive(' ', $response);`

with this:

```php
  $code2parse = implode_recursive(' ', $response);
  runDebug(__FILE__, __FUNCTION__, __LINE__, "PHP code to run: |$code2parse|", 2);

  ob_start();
  eval($code2parse);
  $response_string = ob_get_contents();
  ob_end_clean();
```
**WARNING!!!**  This code contains absolutely NO checks for security, so can constitute a risk to use. Careful consideration of those risks should be taken before implementing it. In other words, use it at your own risk.

**Comment by Dave-Morton** [comment]
It's been more than a month without any further information, so I'm closing this issue for now. Please reopen it if you have anything more to add.
