### ISSUE TITLE
Returns no string on user defined input

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#135]
No string is returned when reading from aiml_userdefined table. Although pattern exist in the table, however it's just a reputation of what the user types.

Eg: 
<category><pattern>WHO IS FROM USA</pattern><template/></category>
is saved in 'aiml' column and "WHO IS FROM USA" in the pattern column.

But no result is returned.

**Comment by Dave-Morton** [comment]
I just set up a specific set of conditions and ran a test, and it passed just fine. However, I found a fundamental flaw in the code that causes this to fail in all cases **except** for the very specific situation that I set up. The stored categories in the aiml_userdefined table is keyed to a user ID that isn't tied to the conversation itself. I'll work on correcting this over the weekend. In the meantime there isn't much that can be done to work around the problem. Sorry.

**Comment by Dave-Morton** [comment]
A bit of further research into this revealed that in order to "properly" fix this the aiml_userdefined table will have to go through a minor change to it's structure to accommodate using the conversation ID, which is an alpha-numeric string, instead of the user ID, which is an integer. As such, I'll have to increment the version number and create a patch file to make the adjustment. This will require a bit of effort and time to implement, so it may not be completed this weekend, but I'll get it done as quickly as I can.

**Comment by tbenjis** [comment]
Thanks, that seems good

**Comment by Dave-Morton** [comment]
Ok, so it took less time than I had thought. the update process should simply be to download the new version from the DEV branch, unzip it, upload it to your server, and then just run it from the root folder of the install (e.g. path/to/program-o/index.php) to activate the patch. The patch file is self deleting on completion, and will update the table structure as needed, returning control to index.php. I've tested it on both Windows and Linux installs, and it seems to do the job correctly. Please let me know if you have any problems.

**Comment by Dave-Morton** [comment]
@tbenjis has the fix corrected the problem for you?

**Comment by tbenjis** [comment]
Yes it did, thanks.
