### ISSUE TITLE
i have a problem in install

### ISSUE THREAD

**Issue by ddongsu** [Program-O/Program-O#145]
Hi i'm Korea university student. plz understand that my english skills are bad.  i downloaded  Program-O file on Github.  i followed install process. but i can't make Database automatic.
page show me that just they can't find page. i filled in form from /install/install_tpl file. 
what can i do this situation?

**Comment by Dave-Morton** [comment]
You should never have to alter the install.tpl.htm file, as that file is simply a template for outputting content from the install script itself. If you've changed that file, I suggest uploading a fresh version of it to your server and just navigating your web browser to your Program O install. the install process is automatic, and does not need to have any files changed before you start. If you have problems with the install, please refer to [this page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) for information about the best way to help us to help you to resolve your issues.

**Comment by ddongsu** [comment]
thanks for your reply.
i  try download repeatly followed your comment.  i can see this message " ERR_FILE_NOT_FOUND" after click the submit save button ( this button is assosiated about DB making page)
this is my path " file:///C:/APM_Setup/htdocs/Program-O-master/Program-O-master/install/[PHP_SELF]"
i think that it doesn't connect with PHP file.
i don't alter any files. it's originally file downloaded by Github.

**Comment by Dave-Morton** [comment]
Ok, the `[PHP_SELF]` bothers me a bit, so I have to ask what software is in use. Please provide the following information:

1.) OS (Windows) version
2.) IIS or Apache? (version would also help)
3.) PHP version
4.) While we're at it, MySQL version

the fact that `[PHP_SELF]` (which is a replacement token) isn't being replaced by a variable during the install process is evidence that something isn't compatible with Program O, and we need to find out what that is. Program O has been tested with IIS versions from 5.[something, I think 6] to IIS 7, and with Apache versions from 2.0 to the latest as of a month ago, with no problems, and with PHP versions 5.3 to 5.6 (I haven't yet tried it with PHP 7, but that's in the planning stages). Once I get the information requested, I'll create a server that comes as close as possible to your setup and test it myself so that I have the best chance of duplicating your problem. Till then there isn't a lot to be done.

**Comment by ddongsu** [comment]
my current OS(windows) version is 7
Apache version 2.2.14
when i wrote above comment ( PHP version 5.2.12 ) 
now I upgrade to 5.6 version  10 minute ago ( but it's same case )
Mysql version is 5.1.41

**Comment by Dave-Morton** [comment]
Well, the upgrade  to PHP 5.6 is a step in the right direction. Let's try this. Unzip a freshly downloaded version of Program O from the DEV branch (https://github.com/Program-O/Program-O/archive/dev.zip) into a completely different folder, such as `C:/APM_Setup/htdocs/chatbot` (make sure that you only extract the files themselves, not the `Program-O-dev` folder that contains all of the files), then run the install script from that new location, and see how that goes.

**Comment by Program-O** [comment]
closing over 30 days without a response.
