### ISSUE TITLE
You can't have a conversation without saying something. Please try again.

### ISSUE THREAD

**Issue by Nerdcoat** [Program-O/Program-O#146]
After a fresh installation.
I go to talk, input a test input and test it.
GUI was XML. Browser was latest FireFox.

In the logs:

(gui.xml.error.log)
> [20-Jul-2016 16:05:14 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /gui/xml/index.php:69
Stack trace:
#0 /gui/xml/index.php(69): SimpleXMLElement->__construct('')
#1 {main}
  thrown in gui/xml/index.php on line 69

(XML.GUI.error.log)
> $data = $data = $data = $data = $data = $data = $data = 

After release that a incorrect url to the api from the auto install was set (a missing / ),
a new file appears: error.log which says:

> [20-Jul-2016 17:08:48 Europe/Berlin] PHP Parse error:  syntax error, unexpected '[' in chatbot/core/aiml/parse_aiml_as_XML.php on line 632

the line with the error was:

>     $starArray = ['~<star[ ]?/>~i', '~<star index="\d+"[ ]?\/>~'];

**Comment by Dave-Morton** [comment]
I just tested this on my development server, which is a Windows/Apache setup, and don't see the problem. Can you please provide information about your server setup so that I can test the issue in an environment that more closely matches what you have? I'll need both OS and server software type and version (please note whether each is 64 bit), PHP version and MySQL version.

**Comment by Nerdcoat** [comment]
Linux
PHP Version 	5.3.29 
Linux 2.6.32-5-amd64
MySQL Client API version 	5.1.73 

I think the PHP version can a the problem, right?

**Comment by Dave-Morton** [comment]
No, that falls within the minimum requirements (e.g. 5.3.x+)

Since you're on a *nix box, I'm assuming Apache is the server software, so just the version would be helpful. I can show you how to obtain that info if you like.

 I also need to know which *flavor* of Linux you're using (e.g. Red Hat, Ubuntu, etc.)

Your MySQL server closely matches mine, so I don't have to set up a whole new database, thank goodness. That's the hardest part of building a new testing server. :)

**Comment by Nerdcoat** [comment]
I am on a webhost so I made an php info. :)
_SERVER["SERVER_SOFTWARE"]	Apache/2.2.16

**Comment by Dave-Morton** [comment]
Ok, so it looks like Debian, as well (I googled the version number), and that pretty much matches one of the servers I already have set up. I'll need about an hour (it's time for breakfast, according to my stomach) to test it out. I'll report back with my findings.

**Comment by Nerdcoat** [comment]
No need to be in a rush, take your time! :)

**Comment by Dave-Morton** [comment]
When I fired up my Debian server I noticed the same problem in the XML GUI, so I made a few minor modifications and found that my problem was one of permissions with writing to the error log. This is not likely to be the exact same problem as yours, since all of my virtual machine servers use SAMBA shared links to the same folder on my dev machine, but I'm still investigating things.

**Comment by Nerdcoat** [comment]
Youre a hero! I know that you will solve the strange error. If I can help investigating, feel free!

**Comment by Dave-Morton** [comment]
**AHA!** I'm now getting the same error that you're seeing:

`HP Parse error:  syntax error, unexpected '[' in /var/www/git/Program-O/chatbot/core/aiml/parse_aiml_as_XML.php on line 632`

Strange that the RegEx works just fine in other server environments, but not in Debian. I'll have to work out a different RegEx pattern.

**Comment by Dave-Morton** [comment]
I've located the problem. It seems that some of the new code that I had added wasn't supported in PHP 5.3, and so choked. I've replaced the code that was causing the issue with "older version-friendly" alternatives, and it seems to be working fine now. I'll push a change in a few moments.

**Comment by Nerdcoat** [comment]
May a req of a higher php would be better for future updates? But I am glad that you found the error again (I am the dude who wrotes you the mails some days before btw)! Thanks for all your work!

**Comment by Dave-Morton** [comment]
No, I've already had to update the PHP requirements several times before, and I don't want to do so at this point because a lot of hosting providers still use PHP 5.3 and I don't want to cause people to either change providers or lose their chatbots. the changes were minor, and didn't affect functionality, so it's no problem. :)

**Comment by Dave-Morton** [comment]
The change is up, on the DEV branch. Only the file parse_aiml_as_XML.php was affected, so you're able to just upload that one file to your server to fix the issue. Please let me know how it works out.

**Comment by Nerdcoat** [comment]
It works like a charm! And no error logs! You are the man!

**Comment by Dave-Morton** [comment]
Thanks for that. :)
