### ISSUE TITLE
[feature req] IP instead of name

### ISSUE THREAD

**Issue by Maik-Thiele** [Program-O/Program-O#152]
I wish to see the IP of the user who chat with the bot,
instead of the same "User: Seeker".

**Comment by Dave-Morton** [comment]
I'll have to think on this one, to figure out the best way to handle it. I may need a few days to work this out.

**Comment by Nerdcoat** [comment]
Everything is fine, take your time! :)

**Comment by Program-O** [comment]
closed over 30 days without a response, please feel free to open again if you have not resolved this

**Comment by Dave-Morton** [comment]
Ok, I've added a feature to allow this to happen, and it's really easy to implement:
1. Get the latest version from the [__DEV__](https://github.com/Program-O/Program-O/tree/dev) branch
2. In the Bot Selection Page, choose the chatbot you wish to use
3. In the Unknown User field, enter [IP] (nothing else)
4. Hit Update
5. Reset the chatbot

From then until changed again, that chatbot wul use the client's IP address instead of an assigned name whenever a user's name is unknown.
