### ISSUE TITLE
Clear conversations via cron jobs

### ISSUE THREAD

**Issue by tbenjis** [Program-O/Program-O#156]
This might help users with large conversations or active users. You might want to schedule a cronjob maybe monthly to delete all conversations and free-up space on the server. We can also include this option in the admin section.

```
<?php
/* clearlogs.php */

$sql_host = 'localhost';
$sql_db = 'db_name';
$sql_user = 'user';
$sql_pass = 'pwd';
$con = @mysql_connect($sql_host,$sql_user,$sql_pass);
mysql_select_db($sql_name,$con);

//truncate users and logs table
mysql_query('TRUNCATE TABLE conversation_log;');
mysql_query('ALTER TABLE `conversation_log` AUTO_INCREMENT = 1;');
mysql_query('TRUNCATE TABLE users;');
mysql_query('ALTER TABLE `users` AUTO_INCREMENT = 1;');
mysql_query('TRUNCATE TABLE client_properties;');
mysql_query('ALTER TABLE `client_properties ` AUTO_INCREMENT = 1;');
mysql_query('TRUNCATE TABLE aiml_userdefined;');
mysql_query('ALTER TABLE `aiml_userdefined ` AUTO_INCREMENT = 1;');


//delete log files
$fullPath = __DIR__ . "/chatbot/debug/" ;
array_map('unlink', glob( "$fullPath*.txt"));

echo "Completed";
?>
```

**Comment by Dave-Morton** [comment]
I'll put this on the ToDo list, but the code will have to be altered a bit to bring it up to date with security best practices. Using mysql_* functions has been known to be insecure for a number of years now. Also, given that there is a "last_update" field in the users table, it would be better to simply delete users that haven't been active for 30+ days, rather than simply truncating the table. The same could be done for conversations more than a month old, and the entire process could even be done through the script itself, without having to create a cron job.  As for the log files, I'll work out a way to delete the files from within the log file viewer. I wouldn't want to have those files automatically deleted for *any* reason. they were created for a good reason, after all. :)

**Comment by tbenjis** [comment]
Oh great! Seems like a better approach. Thanks.

**Comment by Dave-Morton** [comment]
You are most welcome. I've already added the tasks to the ToDo list, and am looking right now at putting in a link in the debug file viewer to delete the selected file, just to see how it will work. When successful, I'll do the same thing to the log file viewer. the rest will have to wait on the redesign of the admin page script. I've had a feature request that will require a full refactoring of the code, so that's the best time to do the rest of this. For now, I'll be closing this issue, seeing as I have the tasks recorded.
