### ISSUE TITLE
I have a trouble in foreign language which sentence with no space character between the words?

### ISSUE THREAD

**Issue by longcnn** [Program-O/Program-O#157]
I have a trouble in foreign language which sentence with no space character between the words, like chinese or orthers.  
I tried the  Word Segmentation function to split the sentence, the process like the graph below:  
![1](https://cloud.githubusercontent.com/assets/4423477/17236480/d4f72a5a-557b-11e6-846c-bed7a8b5a3cd.jpg)
So,I modified the file find_aiml.php in 7-8 positions:
// $words = explode(" ", $sentence); // This is not suitable for Chinese, so replace it  
to  
$words = get_Chinese_SegmentedWords($sentence);  

It worked with some problems, anything i missed or other way i can try?

**Comment by Dave-Morton** [comment]
Since I'm not even a little bit familiar with the syntax of Chinese, I don't really know how to advise you in this. I'm assuming that get_Chinese_SegmentedWords is a function that was created somewhere? Because I can't seem to find it in any PHP reference. I found a [Stack Overflow article](http://stackoverflow.com/questions/13387239/how-can-i-explode-mb-split-preg-split-a-chinese-string-with-a-chinese-perio) about splittng Chinese text on the Full Stop character when the character set is GB 18030, and it seems that the trouble the poster is having may be similar, but again, as I have no familiarity with Chinese, I don't know for sure.

**Comment by longcnn** [comment]
I fixed it ,Thanks!

**Comment by Dave-Morton** [comment]
It's great that you fixed it, but what did you do? This will certainly prove useful for others in the future, so would you mind sharing? :)

**Comment by longcnn** [comment]
I followed the clue of  Debug File of Program-O, some error by  my  careless, just like $word and $words!

**Comment by longcnn** [comment]
Word Segmentation based phpanalysis.
