### ISSUE TITLE
Unable to upload AIML to program-o

### ISSUE THREAD

**Issue by pranavlal** [Program-O/Program-O#163]
Hi,

I am unable to upload AIML files to my Program-O installation. This installation is within a virtual machine. The machine is running 
Ubuntu 16.04. The iso file name I used is ubuntu-16.04.1-desktop-amd64.iso. It is using PHP 7.5 I believe. 
I am using nginx as the web server. I am attaching the error.log from nginx with this report.

**Comment by pranavlal** [comment]
[error-log.txt](https://github.com/Program-O/Program-O/files/487648/error-log.txt)
To continue the report, I was able to create the database and the administrative interface appears to be running. These are the commands I ran to install Program-O and get it working.
sudo git clone https://github.com/Program-O/Program-O.git
CREATE USER 'bot'@'localhost' IDENTIFIED BY 'bot123';

GRANT ALL PRIVILEGES ON * . * TO 'bot'@'localhost';
chmod 0755 config
chmod 0755 logs
chmod 0755 Program-O
chmod 0755 admin
chmod 0755 debug
sudo chown -R www-data:www-data /var/www/html
sudo apt-get install php7.0-mbstring
sudo systemctl restart apache2.service
sudo systemctl stop apache2.service
http://192.168.88.14/Program-O/install/install_programo.php 

Finally, I am happy to send the virtual machine to you if that will help in debugging. We will need to figure out how to transfer such a large file.

**Comment by Dave-Morton** [comment]
From the looks of the error logs you have a permissions problem in the Program O folder. Try entering the following into your terminal:

`sudo find /var/www/html/Program-O -type -d -exec chmod 755 {} \;`

this will recursively set permissions to all folders within your Program O install to the correct level. After running that command, clear or delete the error logs and try again. If you still cannot upload AIML files, please post any new error log entries here, and we'll look further.

**Comment by pranavlal** [comment]
Chmod -R 755 Program-O

 

The files do not upload and even stranger still,  the error.log is blank so I do not know what to send you.

I don’t know if the attached screen shot will help;.

**Comment by Dave-Morton** [comment]
No, it did not show up. It's best when wishing to add additional images or files to actually post to https://github.com/Program-O/Program-O/issues/163 rather than replying to the notification email. That way you have the ability to use the tools provided on the page to add additional data.

**Comment by pranavlal** [comment]
ok, I am now trying from the github interface.
![program-o_capture_001_23092016_053545](https://cloud.githubusercontent.com/assets/8674563/18786760/318843d6-81bd-11e6-8800-4af769d892cc.jpg)

**Comment by Dave-Morton** [comment]
Ah. I see. a blank page is decidedly not good. And you don't have any entries in the Program O error logs? In version 2.6.3 there is a link in the navigation sidebar that reads "View the Logs". Clicking on that will take you to the log file viewer. Once you log into that page (it's a separate login from the admin page, but uses the same credentials), you should be presented with a dropdown list of all existing error logs for Program O. If there are no files listed, then I don't know what to tell you, since I have no way to investigate further.

**Comment by Dave-Morton** [comment]
By the way, I'm going to set up a new VM using Ubuntu 16.04, nginx and PHP 7, so that I can see if I can replicate the results. this may take me a while, though, because I have a VERY full schedule today. but I'll let you know what I find.

**Comment by pranavlal** [comment]
Hi Dave,
No go on the Program-O logs. The logs folder appears to be empty and I get a server not found error message when I login into the log viewer. I checked the nginx error.log but that file was also blank.

**Comment by Dave-Morton** [comment]
Ok, then I'll just have to get this VM set up so that I can investigate further. The only other option would be to create a VPN connection to your VM, and I don't think that's something that should be discussed publicly, for obvious reasons. :) I just got Ubuntu Desktop 16.04 installed on a new VM, but I have a lot of other prep work to do still.

**Comment by pranavlal** [comment]
Hi Dave,
In line with your suggestion of starting fresh on the AIML forum, I have created a fresh virtual machine and have installed nginx, mysql and php. All of this is working correctly. My web root is set to /var/www/html 
My question relates to folder ownership. As of now, everything is owned by root. This is not a good security practice. Am I correct in thinking that the user www-data should own the Program-O folder and all folders under it? This could well be my problem.

**Comment by Dave-Morton** [comment]
It's hard to say, seeing as neither the error message itself nor the stack trace are very informative. I've got the VM running 16.04, but I'm having a bit of trouble with nginx, since Apache was already installed. I'm sorting it out, but it takes a little time since I'm not used to nginx.

**Comment by Dave-Morton** [comment]
Hmmm... I thought sure I had posted a response here, but it seems that it didn't "stick". Oh well. Take 2!

I just got the VM working with Ubuntu 16.04 and PHP7, but I haven't yet tried to see if I could upload any AIML files. As it's nearly 4AM now, I've run out of time to do so (I have to "get up" in an hour and a half, and I haven't even been to bed yet! :O ) I don't yet know if any of the necessary PHP extensions (PDO, mbstring, etc.) are loaded yet, but I'll be able to check that out tomorrow (well, later today, actually). I'll keep you posted.

**Comment by Dave-Morton** [comment]
Ok, I've made some progress. You may be having permissions issues with nginx's log files. I did, and that was what was causing no log file entries. You should not have the same problem with your install (long story, which I'll explain below), but it's a good idea to check, just to be sure. You can check the user/group of nginx with this command:

`ps -ef | grep nginx`

the output should look something like this:

> # ps -ef | grep nginx
> root      1013     1  0 02:20 ?        00:00:00 nginx: master process /usr/sbin/nginx -g daemon on;
> master_process on;
> **www-data**    14257  1013  0 04:43 ?        00:00:00 nginx: worker process
> root     16706  5134  0 04:57 pts/4    00:00:00 grep --color=auto nginx

Please note the **bold** text. This is the user/group of the nginx worker thread, and what *should* be the owner of the log folder, as well. If they're different, you can change either one to match the other, though it's probably easier to change the owner of the folder.

Now the reason I found this is because I was getting internal server errors when trying to use the Program O API that contained an already existing chatbot, but no error log entries were being created. Once I got the error logging problem fixed, I found that PHP was missing a few extensions (zip, DOM, SimpleXML and mbstring, so far - I'm still testing). I suspect that this is also the case with your PHP install. What I did to correct that was to enter the following commands into the terminal:

`sudo apt install -y php7.0-mbstring php7.0-zip php7.0-xml`
`service nginx reload`

this corrected the missing extensions so far. There may be more, and if there are I'll post what they are and how to get them installed.

**Comment by pranavlal** [comment]
Hi Dave,
mbstring is not installed by default but your installation page warned me about it so I installed it for php 7. I did not get any other warnings about missing extensions.
I used the instructions at the below link to get everything working.
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-in-ubuntu-16-04
I am also keeping notes so that I can write a more detailed installation page. <smile

Many thanks for all the troubleshooting help

**Comment by pranavlal** [comment]
Hi again,
I have made progress. After applying the extensions you have suggested and changing the ownership of the /var/log/nginx folder I am able to get errors when I upload my AIML file. Program-O does not like the <set> tag. My AIML is correct because it works with program-ab.

**Comment by Dave-Morton** [comment]
Program O doesn't like the `<set>` tag because it's not an AIML 1.0 tag. The current version of Program O cannot handle AIML 2.0 tags, which is why it rejects it.

**Comment by pranavlal** [comment]
Many thanks for the clarification Dave. Do you have any plans of upgrading Program-O to handle AIML 2.0?

**Comment by Dave-Morton** [comment]
I've been working on Program O version 3 for almost 5 years now, but between life's little (or not-so-little) detours, motorcycle accidents, work and school it's been very hard to spend any real time on it. I have a *mostly* functional pre-alpha prototype working, which is more than I could have said 2 months ago, but it's a very long way from being able to really use. Still, it supports AIML 2.0, and the `<map>` and `<set>` tags work as expected, but the zero-length wildcards still don't work, and I have to coax a **LOT** more efficiency out of the script (right now volleys take upwards of 5-30 seconds to execute). I've got my work cut out for me, that's for sure. :D

**Comment by AlekzNet** [comment]
I wonder how easy/difficult/impossible would it be to implement an "interim" solution - "AIML1.5" in Program O 2.x?  For example, just some tags features that do not require serious or complete redesigning, like what you are doing with v3?

**Comment by Dave-Morton** [comment]
Sorry about the long delay in posting, folks. School is headed towards finals, and the workload has been horrible.

@AlekzNet if you use the Custom Tag feature, you could replicate the functionality of _any_ AIML 2.0 tag, but that would require some moderately deep expertise in PHP programming. If version 3 of Program O were to use the same structure that it currently does, then such functions could be migrated into the core code, rather than staying within the Custom Tags section, but unless the performance issues cannot be resolved with the new version, the current codebase will be completely scrapped, so writing said custom tag functions wouldn't be carried over, and might be construed as a waste of time. Still, that's _one_ way to add AIML 2.0 support to Program O. :D

**Comment by Dave-Morton** [comment]
@pranavlal I've made some changes to a few things that may take care of this issue. Please download the latest version from the DEV branch and see if that takes care of it. Thanks.
