### ISSUE TITLE
<think> inside and outside of <template>

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#165]
Can `<think>` be placed outside of  `<template>`? The following construction does not validate in the latest 2.6, but worked in 2.4.:
````xml
<category>
  <pattern>Topictest</pattern>
  <template>Topictest </template>
  <think> <set name="topic">test</set></think> 
</category>
````

**Comment by Dave-Morton** [comment]
No, that will not work in version 2.6 (and should never have worked in 2.4, for that matter) because it's not within the `<template>` tag, and **not** valid AIML. If you have AIML files that are constructed that way, you'll need to correct them to place all response content *inside* the `<template>` tag.

**Comment by AlekzNet** [comment]
OK, Dave, clear enough. Thanks much for the clarification! Reformatting the files now ;)

**Comment by Dave-Morton** [comment]
No worries. If you have any other issues please let us know. :)
