### ISSUE TITLE
<person/> and <person2/> inconsistency 

### ISSUE THREAD

**Issue by AlekzNet** [Program-O/Program-O#168]
I'm not quite sure how it should be implemented according to the standard (the standard says: "...left up to the implementation"), but this is a bit confusing (or, rather, not quite consistent):

``` xml
<category>
    <pattern>test person _</pattern>
    <template><br/>
        Input:<star/><br/>
        Person:<person/><br/>
        Person2:<person2/><br/>
    </template>
</category>
```

Results:

User: test person I
Bot:
Input: I
Person: it
Person2: you 

User: test person you
Bot:
Input: YOU
Person: YOU
Person2: I 

User: test person he
Bot:
Input: HE
Person: HE
Person2: HE

User: test person I am
Bot:
Input: I AM
Person: it is
Person2: you are

User: test person you are
Bot:
Input: YOU ARE
Person: YOU ARE
Person2: am I 

User: test person am I
Bot:
Input: AM I
Person: is it
Person2: are you 

User: test person I have
Bot:
Input: I HAVE
Person: it HAVE
Person2: you HAVE

User: test person you have
Bot:
Input: YOU HAVE
Person: YOU HAVE
Person2: I HAVE 

User: test person she has
Bot:
Input: SHE HAS
Person: SHE HAS
Person2: SHE HAS 

The questions are:
- Is there a "general agreement" how to transform forms?
- Should the order be reversed for "you are" => "am I"? It's not reversed for "you have" => "I have".
- While "I" => "he" or "she" is not quite clear, I think "he/she" should be transformed by `<person\>` into "I" 
- Using low- or uppercase seems to be quite random

**Comment by Dave-Morton** [comment]
This has been an issue from the very beginning. It's been much improved over the years, but it's still not completely correct. If you have any skill with PHP and a firm grasp of grammar with regard to person-tense, you're strongly encouraged to see what you can do with the code.

Part of the problem is with the tags themselves. the `<person>` tag does transformations from first person to third person and vice-versa, while the `<person2>` tag does so from first person to second and back. While `<person2>` makes sense as a tag name, `<person>`, by itself, is counter-intuitive. Personally I think it should have been `<person2>` and `<person3>`, but I didn't write the standard.

**Comment by Dave-Morton** [comment]
Thias still needs attention, so I'm leaving this open for now. @AlekzNet if you have any ideas, I'd be glad to hear them.

**Comment by AlekzNet** [comment]
To be honest, due to lack of time (ha, always!) I did not look into it properly.

**Comment by Dave-Morton** [comment]
Trust me, I understand that. Would we all have had the time, Program O would be much farther along in the development process. :)

**Comment by tringate** [comment]
@Dave-Morton, I took some time to look into this and found an error.  The person and person2 tags have been reversed to process the incorrect first to second and first to third conversions.  In the file parse_aiml_as_xml.php at 
line: 998 $response = swapPerson($convoArr, 3, $response_string); the value "3" should be "2" and at 
line: 1017 $response = swapPerson($convoArr, 2, $response_string); the value "2" should be "3".
The function "swapPerson" is being sent the wrong value so the two tags are actually work as the other tag should be working.

The person tag should swap 1st & 2nd person
The person2 tag should swap 1st & 3rd person

I suspect that some may have discovered this reversal in programo and have altered their AIML to account for this mistake.  It may require them to edit their AIML but programo should comply with AIML 1.0.1 so that proper written AIML will work properly.

I wrote a small AIML category to test the conversions that are in the code, and easily discovered the two tags were swapped in what they were doing.

Here is the output with the current code.

Slow Putzo: testperson
April Genie: 
First person to second person 
Input: I am PERSON TAG: it is PERSON2 TAG: you are 
Input: am I PERSON TAG: is it PERSON2 TAG: are you 
Input: was I PERSON TAG: was it PERSON2 TAG: were you 
Input: I PERSON TAG: it PERSON2 TAG: you 
Input: my PERSON TAG: its PERSON2 TAG: your 
Input: mine PERSON TAG: its PERSON2 TAG: yours 
Input: myself PERSON TAG: itself PERSON2 TAG: yourself 
Input: your PERSON TAG: your PERSON2 TAG: my 
Input: me PERSON TAG: it PERSON2 TAG: you 
Input: ourselves PERSON TAG: themselves PERSON2 TAG: yourselves 
Input: we PERSON TAG: they PERSON2 TAG: you 
Input: us PERSON TAG: us PERSON2 TAG: you 
Input: ours PERSON TAG: theirs PERSON2 TAG: yours 
Input: our PERSON TAG: their PERSON2 TAG: your 

Second person to first person 
Input: are you PERSON TAG: are you PERSON2 TAG: I am 
Input: you are PERSON TAG: you are PERSON2 TAG: am I 
Input: were you PERSON TAG: were you PERSON2 TAG: was I 
Input: you PERSON TAG: you PERSON2 TAG: I 
Input: your PERSON TAG: your PERSON2 TAG: my 
Input: yours PERSON TAG: yours PERSON2 TAG: mine 
Input: yourself PERSON TAG: yourself PERSON2 TAG: myself 
Input: thy PERSON TAG: thy PERSON2 TAG: my 
Input: yourselves PERSON TAG: yourselves PERSON2 TAG: ourselves 

I have not actually looked at the section doing the First person to third person yet, but the results are in the above listing due to I tested both tags for each input.

Making this change will go a long way at getting programo functioning correctly per the AIML 1.0.1 spec.

**Comment by tringate** [comment]
@Dave-Morton 

As for the case change I see no reason the conversion code would change the case.  The only defined case in the conversion is to make "i" an uppercase I since "I" is always an uppercase when it refers to self.  The other words are all in lowercase in the conversions, so something else changed the case in the first example the original reported gave.

The only conversion error I believe that exists in the conversions I tested is "thy" for "me"  Normally when you say"thy shall behave" strange language unless you are writing the bible, the conversion should be "I shall behave" not "me shall behave".  I guess if you are writing a bad western with the stereo type native Americans "me" would be fine.

Since that conversion would rarely ever occur in normal conversation, I just ignored it.

To make it a perfect routine conversion is probably not worth the effort unless you are really into english.

Tom

**Comment by tringate** [comment]
@Dave-Morton 

One further comment about these two tags.  While I could not find an exact functional description of what each tag should do in the 1.0.1 spec, I referenced my old notes back when I did the move from 0.,9 to 1.0 AIML and in those notes I did state the tag was to do the reverse from 2nd back to 1st person.  No such wording exists in the 1.0.1 spec that I was able to find.  I do believe it is "presumed" the two tags would do the conversion in both directions, and programo does that for the testing of first to second that I tested.

**Comment by Dave-Morton** [comment]
@tringate Just to let you know, your assumptions about the functionality of the `<person>` and `<person2>` tags are incorrect. The following is from the [ALICE AIML Reference Manual](http://www.alicebot.org/documentation/aiml-reference.html#person):

>The <person> and <person2> tags indicate a place where the AIML interpreter changes the personal pronouns in a sentence.

> `<person2> X </person2>` change X from 1st to 2nd person 
> `<person> X </person>` exchange 1st and 3rd person

From your posts, I __DO__ see what appear to be some errors, but overall the functionality is correct, I believe. Let's discuss this over Skype before decisions are made over what's to be done with this.

**Comment by tringate** [comment]
Dave,

I had a late dinner but can’t call you because it shows you as off-line.  I have skype up now.

Here is as reference to a AIML 1.0.1 tag chart, and it confirms my understanding which matches the original 0.9 and 1.0 specs too.

http://www.alicebot.org/documentation/aiml101.html

I would be interested in finding where you found the other information.

I kind of remember reading something from Dr. Wallace just a few days ago talking about this same thing too, so I’ll see if I can find that.  All of the original AIML I have only used person2 in 2 categories and they were in displaying the topic.  All the other conversions were the person tag.


The blurb I read by Wallace was explaining why the person2 tag was called “2” and he said it was because it was the “second tag that was added after the original person tag so it was named “2”.

Tom

**Comment by tringate** [comment]
Dave,

Here is the write up at the a.l.i.c.e foundation for spec 1.0.1.

http://www.alicebot.org/TR/2011/#section-person2
Artificial Intelligence Markup Language (AIML)
Version 1.0.1
A.L.I.C.E. AI Foundation
Official AIML 1.0.1 standard
Adopted October 30, 2011 (rev 008)
This document resides at:

http://alicebot.org/TR/2011/WD-aiml/index.html

Working Draft versions:

http://alicebot.org/TR/2005/WD-aiml-1.0.1-008.html

http://alicebot.org/TR/2001/WD-aiml-1.0.1-20010218-007.html

http://alicebot.org/TR/2001/WD-aiml-1.0.1-20011018-005.html

http://alicebot.org/TR/2001/WD-aiml-1.0-20010926-004.html

http://alicebot.org/TR/2001/WD-aiml-1.0-20010926-003.html

Creator of AIML:

Richard Wallace

Editor of this Document:

Richard Wallace

Original Author of this Document(*):

Noel Bush

Contributors to source material for this document:

Thomas Ringate, Anthony Taylor, Jon Baer, Noel Bush(*)

(*) - Note: As of 2/2005, most of the material in this document was written by former A. I. Foundation member Noel Bush. His outstanding contribution to this documentation and standardization effort is greatly appreciated by the A. I. Foundation and by members of the A.L.I.C.E. AI community.

Copyright © A.L.I.C.E. AI Foundation, All Rights Reserved. A.L.I.C.E. AI Foundation software licensing rules apply.


7.6. Transformational elements
AIML defines several transformational elements, which instruct the AIML interpreter to transform the result of processing the contents of the transformational element into another value according to a lookup table. The implementation of transformational elements is left up to the implementation.

7.6.1. Person2
The person2 element instructs the AIML interpreter to:

  1.. replace words with first-person aspect in the result of processing the contents of the person2 element with words with the grammatically-corresponding third-person aspect; and 
  2.. replace words with third-person aspect in the result of processing the contents of the person2 element with words with the grammatically-corresponding first-person aspect.
The definition of "grammatically-corresponding" is left up to the implementation.



<aiml:person2>

   

</aiml:person2>

Historically, implementations of person2 have dealt with pronouns, likely due to the fact that most AIML has been written in English. However, the decision about whether to transform the person2 aspect of other words is left up to the implementation.

7.6.2. Person
The person element instructs the AIML interpreter to:

  1.. replace words with first-person aspect in the result of processing the contents of the person element with words with the grammatically-corresponding second-person aspect; and 
  2.. replace words with second-person aspect in the result of processing the contents of the person element with words with the grammatically-corresponding first-person aspect.
The definition of "grammatically-corresponding" is left up to the implementation.



<aiml:person>

   

</aiml:person>

Historically, implementations of person have dealt with pronouns, likely due to the fact that most AIML has been written in English. However, the decision about whether to transform the person aspect of other words is left up to the implementation.

**Comment by tringate** [comment]
Dave,

I just noticed the link in this email, and now I understand your understanding.  That was the working document as we converted from 0.9 to 1.0 and it was from September 2001.  I never finished updating that particular manual and as you can see in the description of the two tags there is conflicting information even in describing it.

At that time, the work of adding the person2 tag had not really been tested or even agreed to so I never tried to clear up the mess.  Originally the person tag tried to do both and the wording in that old document kind of tried to explain how the old original person tag worked more than how it was being evolved.

The reference I sent to you in the later document was the eventual results of the committee they formed to iron out the discrepancies we had between program B, program D and a few other versions that were being worked on.

The official AIML 1.0.1 has cleared up the mess and does coincide with how I understood the two tags would be made to work.  I am amazed that no one ever finished that document but there was so much turmoil at the foundation at that time and many of us left the project mid stream while the politics were ironed out.

Pedro and I went off and finished the implementation of the AIML 1.0 as we both understood it and gave both the program and the finished AIML set back to the foundation for them to do with as they desired.  It would appear by looking at these old documents they did nothing with it until Noel started the AIML 1.0.1 document in 2005 with a more consistent format and change control.  I don’t see any new tags added by 1.0.1, more a clean up of the mess we all knew we had with no firm documented specification to write the software to.

Tom

**Comment by Dave-Morton** [comment]
@tringate and I hashed thos out via Skype a while ago, but the issue never got closed. Till now, that is. :)
