### ISSUE TITLE
Problem with star index

### ISSUE THREAD

**Issue by giuliopons** [Program-O/Program-O#172]
Hi, I'm trying to get user name.

The second pattern should match phrases  like "**Hi! my name is John**", but it doesn't work:

```
<category>
    <pattern>MY NAME IS *</pattern>
    <template>Nice to meet you <set name="nome"><star/></set></template>
</category>
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star index="2"/></srai></template>
</category>
```

I've also tried different small variations, such as:

```
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star index="1"/></srai></template>
</category>
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star index="2"/></srai></template>
</category>
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star /></srai></template>
</category>
<category>
    <pattern>* MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star index="2"/></srai></template>
</category>
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star /></srai></template>
</category>
```

Any suggestion to find my error?
Thank you!
Giulio

**Comment by Dave-Morton** [comment]
What sort of response are you getting? And have you looked at the debug files to see what's happening? It would also help to know what your system specs are. The easiest way to provide this information would be to attach the most recent debug file that's generated when you type in "Hi! My name is John!" to your chatbot.

**Comment by giuliopons** [comment]
Here is the log file.
http://www.ku-ku.it/gino/chatbot/debug/pnlocacig1rj4if8kns5lntac7.txt
Now I take a look at the debug file.

When I say "Hi! My name is John" bot says "Nice to meet you HI"

using this:

```
<category>
    <pattern>MY NAME IS *</pattern>
    <template>Nice to meet you <set name="nome"><star/></set></template>
</category>
<category>
    <pattern>_ MY NAME IS *</pattern>
    <template><srai>MY NAME IS <star index="2"/></srai></template>
</category>
```

**Comment by AlekzNet** [comment]
Strange, I'm getting precisely the opposite problem with matching `<that>`, that does not work without the star in front.

**Comment by Dave-Morton** [comment]
@giuliopons I'm getting the same problem, but only when an `<srai>` tag is used, and it appears you have the same problem. I'm looking into this, and I'll keep you posted.

**Comment by giuliopons** [comment]
@Dave-Morton yes, the problem is only with `<srai>`

**Comment by giuliopons** [comment]
Watching carefully the debug file, I've seen that program-o build the new template to search correctly (there is "MY NAME IS JOHN" in the debug file) and match the correct template ("MY NAME IS *") but it uses the old star array, extracted from the first string, which is correctly:
```
Array(
   "1"=>"HI",
   "2"=>"JOHN"
)
```
So I think that the error is that somewhere we need to run `set_wildcards` function again.

**Comment by Dave-Morton** [comment]
I've come to the same conclusion myself, but resetting the star array each time seems to have no effect for some reason (probably because it still runs against the original pattern). What I think needs to happen is to reset the star array in the function `run_srai()`, then run `set_wildcards()` at that point, but against the contents of the `<srai>` tag, rather than the original input. I just haven't had the time to work on it yet.

**Comment by giuliopons** [comment]
Hi @Dave-Morton, I'm trying to found a fix for this problem. Can you tell me if the new string "MY NAME IS JOHN" should be added in the $convoArr['aiml'] array or not? Should I replace the $convoArr['aiml']['user_raw']?

**Comment by giuliopons** [comment]
in the `parse_srai_tag` function I've noticed that the `$srai` variable is **MY NAME IS JOHN** but you pass to the `run_srai` call the modified version `$srai_new` which contains **MY NAME IS **, if:

`$response = run_srai($convoArr, $srai_new);`

becomes

`$response = run_srai($convoArr, $srai);`

it works.

**Comment by Dave-Morton** [comment]
Awesome! I haven't had the time to work on this at all this week, so I'm quite pleased that you took up the challenge. Can you post the modified code here, as well as the filename/line number where the change was made? I'd like to look it over and do some testing.

**Comment by giuliopons** [comment]
I'm not sure that this fix works, this file: [/chatbot/core/aiml/parse_aiml_as_XML.php](https://github.com/Program-O/Program-O/blob/master/chatbot/core/aiml/parse_aiml_as_XML.php), line `643`, change:

`   $response = run_srai($convoArr, $srai_new);`

to

`  $response = run_srai($convoArr, $srai);`

In the above case, $srai_new contains "`MY NAME IS *`", and $srai contains "`MY NAME IS JOHN`".

**Comment by RobertBicknell** [comment]
@giuliopons Just ran into this issue, found and applied your fix - great work!

**Comment by giuliopons** [comment]
Thank you @RobertBicknell - But you have to monitor if this fix causes other problems. I'm not sure if it's right, since in the same function `$srai_new` is created to feed `run_srai` function,

**Comment by RobertBicknell** [comment]
Yes, I saw that your post was circumspect, and so will keep my eyes open.
However, it took quite a while before I decided this was a indeed a bug and
not something I was misunderstanding, so when I started googling it was
without much hope of a resolution, as Program O seems fairly sleepy these
days.... But what do I find? Your very recent comment solves my immediate
problem - remarkable! I will do some more testing.

Thanks and good luck with your development,

Robert

**Comment by AlekzNet** [comment]
I'm not sure what going on here. I have the following:

```xml
<category>
<pattern>Teststar *</pattern>
 <template><srai><star/></srai>
 </template>
</category>

<category>
<pattern>ABCD</pattern>
<template>ABCD</template>
</category>
```

"Teststar ABCD" produces "Your first name is ABCD." How come? Is it only me?

**Comment by AlekzNet** [comment]
Oh, found this:

31-10-2016 16:54:38.62025[4][4] - Elapsed time: 0.010 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][203]
function parse_template_tag does not exist. Parsing tag as text. 

31-10-2016 16:54:38.62028[4][4] - Elapsed time: 0.008 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][190]
Function parse_srai_tag does exist. Processing now. 

Something is missing...

**Comment by AlekzNet** [comment]
This is what happens, Instead of looking for 'ABCD', it looks for '*':

31-10-2016 20:02:34.62315[4][4] - Elapsed time: 0.007 milliseconds
[parse_aiml_as_XML.php][implode_recursive][162]
Imploding complete. Returning 'ABCD' 
-----------------------
31-10-2016 20:02:34.62324[2][4] - Elapsed time: 0.084 milliseconds
[parse_aiml.php][run_srai][359]
Running SRAI. Pattern = '*'. 
-----------------------
31-10-2016 20:02:34.62325[2][4] - Elapsed time: 0.011 milliseconds
[parse_aiml.php][run_srai][371]
Checking for entries in the srai_lookup table. 
-----------------------
31-10-2016 20:02:34.62325[2][4] - Elapsed time: 0.005 milliseconds
[parse_aiml.php][run_srai][372]
google bot_id = 1 
-----------------------
31-10-2016 20:02:34.6233[2][4] - Elapsed time: 0.049 milliseconds
[parse_aiml.php][run_srai][376]
lookup SQL = select `template_id` from `db_aio`.`srai_lookup` where `pattern` = '*' and  bot_id = '1' ; 

-----------------------
31-10-2016 20:02:34.62377[2][4] - Elapsed time: 0.466 milliseconds
[parse_aiml.php][run_srai][378]
Result = Array
(
    [0] => Array
        (
            [template_id] => 16053
        )

)
 
-----------------------
31-10-2016 20:02:34.6238[2][4] - Elapsed time: 0.026 milliseconds
[parse_aiml.php][run_srai][382]
Found 1 rows in lookup table: Array
(
    [0] => Array
        (
            [template_id] => 16053
        )

)
 
-----------------------
31-10-2016 20:02:34.62381[2][4] - Elapsed time: 0.012 milliseconds
[parse_aiml.php][run_srai][384]
Found a matching entry in the lookup table. Using ID# 16053. 
-----------------------
31-10-2016 20:02:34.62399[2][4] - Elapsed time: 0.185 milliseconds
[parse_aiml.php][run_srai][387]
Row found in AIML for ID 16053: Array
(
    [template] => <srai>MY FIRST NAME IS <star/></srai>

**Comment by AlekzNet** [comment]
Aarrrghh... I should've read the thread properly. I though that it's fixed in the latest dev version...

**Comment by AlekzNet** [comment]
Nope. I'm stuck again. After I changed the parse_aiml_as_XML.php the construction above started working, but this one still produced the default answer if I type `xsraitest ABCD`:

```xml
<category>
<pattern>xsraitest  *</pattern>
 <template><srai>xstest <star/></srai></template>
</category>

<category>
<pattern>xstest *</pattern>
 <template>The star is <star/></template>
</category>

<category>
<pattern>xstest</pattern>
 <template>The star is  empty</template>
</category>
```

**Comment by RobertBicknell** [comment]
Whitespace? Try: xsraitest  ABCD

**Comment by AlekzNet** [comment]
Removed all double white spaces around, now getting the following:

```txt
User: xsraitest ABCD
Bot: The star is
```

**Comment by RobertBicknell** [comment]
<template><star/></template>  -  check this (no SRAI) for extra whitespace.
might also check <star index="2"/>

**Comment by AlekzNet** [comment]
Good idea. Checking...

**Comment by AlekzNet** [comment]
No, that works, I checked that already:

```txt
User: xstest ABCD
Bot: The star is ABCD
```
I added the following:
```xml
<category>
<pattern>xstest * *</pattern>
 <template>The stars are <star index="1"/> and <star index="2"/> </template>
</category>
```

But the result is still the same:

```txt
User: xsraitest ABCD
Bot: The star is
```

**Comment by RobertBicknell** [comment]
Well the elephant in the room is that the php fix may create such behaviour
or the bug have already been there (groan), so while it works enough for
me, I am not going to delve into it - but - as a horrible work around, you
can try:

<think><set name="kludgestar"><star/></set></think>

then use <get name="kuldgestar" />

**Comment by AlekzNet** [comment]
Yes indeed. It's "either - or". Just checked :  `$srai_new` works for one construction, but breaks another, `$srai` fixes the latter, but breaks the former. Sigh....

**Comment by AlekzNet** [comment]
OK, the workaround is to use the original version with `$srai_new` and `<sr/>` instead of `<srai><star/></srai>`.

**Comment by AlekzNet** [comment]
This script did the trick:
```sh
for i in *.aiml 
do
cat $i | sed -e 's%<srai> *<star/> *</srai>%<sr/>%g' > /tmp/$i
mv /tmp/$i $i
done
```

**Comment by Dave-Morton** [comment]
So from the sound of it, `<sr/>` works, yet `<srai><star/></srai>` does not? If this is the case, it's a definite bug that needs to be found and fixed. I'll compare the two functions and see if I can get to the bottom of it.

By the way, I should point out that the wildcard characters (both * and _ ) each require *one or more* "words" each in order to match. In other words, `XSTEST * *`  will not match "xstest ABCD" at all, but "xstest ABCD EFGH" will

**Comment by AlekzNet** [comment]
> In other words, XSTEST * * will not match "xstest ABCD" at all, but "xstest ABCD EFGH" will
Yes, I know. As far as I understood @RobertBicknell it was to test the functions - if they correctly passes the arguments and search for correct arguments. In other words, for troubleshooting purposes ;)
