### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by AhilJose** [Program-O/Program-O#183]
Every time I try to install program O the installation fails with the following message

> Cannot connect to the database! SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused 

I am completely new to program O. I don't know why I am seeing this error message.
Help me pls somebody. :)

**Comment by Dave-Morton** [comment]
From the sound of it, you're having difficulties actually connecting to MySQL.

Are you trying to install Program O on a local computer, or on a web host?

**Comment by AhilJose** [comment]
Thanx for replying

I am installing on a local computer (localhost)

**Comment by Dave-Morton** [comment]
Ok, then. I'm going to need some information on your computer. Mainly, I'll need the following:

1.) OS type and version (e.g. Windows 7, Ubuntu 14.04, etc.)
2.) Server software (Apache 2.4, nginx, IIS, etc.)
3.) Do you have phpMyAdmin installed, and if so, what version?
4.) which version of Program O, and which branch did you download it from (MASTER or DEV) 

Once I have this information I can provide some steps to take to investigate and correct the situation.

**Comment by AhilJose** [comment]
I am using 
1. Windows 8
2. Apache 2.4.6
3. Yes I have phpMyAdmin installed and 4.0.4.2
4. And Program O from MASTER

**Comment by Dave-Morton** [comment]
Ok, let's do a little troubleshooting. First off, just for the purposes of testing (and only temporarily) try turning off the Windows firewall and see if that makes a difference. It probably won't, since you have phpMyAdmin and I'm assuming that it's working, but it's worth a try. If that works, then it's a matter of adding a rule to the firewall to allow connections on MySQL's port of 3306. 

The other thing to check (as it isn't listed in the image you've posted) is to make sure that the port for MySQL is configured correctly. That's just about the only other thing that could likely cause that particular error message.  the default port for MySQL is 3306, though I don't know with any degree of certainty whether USBWebServer keeps that default value, so it's a good idea to check it out.

**Comment by AhilJose** [comment]
It worked!
Thanx a lot.

**Comment by Dave-Morton** [comment]
Glad that I was able to help, but what exactly did you end up doing to fix the problem? Someone else at some point could well benefit from learning about it, after all. :)

**Comment by AhilJose** [comment]
> As  you said I just changed the port number of USBWebserver 3307 to 3306 and added in firewall to allow connection on MySQL's port of 3306

And it worked in my Windows 8.

**Comment by Dave-Morton** [comment]
That's perfect. Thanks for sharing that. Until you had posted about it, I hadn't heard of USBWebserver before. I think I'll have to create another virtual machine to check it out. Thanks. :)
