### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by razvanbolintis** [Program-O/Program-O#190]
Hello Dave,

I have followed the instruction from here: https://github.com/Program-O/Program-O/wiki/Installation-Guide
But I receive the following when I try to access the admin section:

Not Found

The requested URL /install/install_programo.php was not found on this server.

It redirects me to the install which I deleted on a previous step as described.

Thank you,
Razvan

**Comment by Dave-Morton** [comment]
It sounds to me as if one of the files or folders that are supposed to be created during the install process was probably not created. It could also be a browser caching issue, so let's start there.

The easiest way to verify a caching issue is to try to navigate to your chatbot while using a different web browser. Most people these days have multiple web browsers, so this should not pose a problem. 

If looking at the page in a new browser doesn't resolve the issue, then try looking in the config folder for the file global_config.php. If it's not there, then this is where your problem lies, and you'll have to restore the install folder and try again. While it's a good idea to make the install folder inaccessible for security reasons, it's often better to first rename it until the chatbot is verified to be up and running, __then__ remove it.

If that file exists, then the next step is to look at the contents of the logs folder. If there are any log files (they all end in .log), then please have a look within them and let me know if there is anything in them that might be relevant.

**Comment by razvanbolintis** [comment]
I repeated the whole process again, this time renaming the install folder as you said and on a different browser and it worked, thank you!
When I try to upload the salutations.aiml file I receive "There was an error moving the file.".

**Comment by Program-O** [comment]
please can you check the permissions of the folder you are uploading to, to make sure it is writeable.
thanks

**Comment by Dave-Morton** [comment]
No further input regarding this issue, so I'm closing it. If you are still having trouble, please start a new issue. Thansk.
