### ISSUE TITLE
Choose a Chatbot and bot_id Question

### ISSUE THREAD

**Issue by tyzenker** [Program-O/Program-O#195]
My 1st question is this:  For the Multi-bot example, it won't let you choose a bot and keeps showing "unknown" in the drop-down box for "Choose a Chatbot".  It keeps defaulting to Bot ID "1".  How can you enable it to show the different bots in the drop-down? 

My 2nd question is:  For the original, single-bot, conversation_start.php example, how do you change the bot_id for that file?  As I stated before, it always defaults to Bot ID "1".   What would I need to change in the conversation_start.php file to make it be Bot ID "2" ?

Everything seems to be working, but it keeps defaulting to Bot ID "1", and won't recognize any of my other Bots.  Can you help?

**Comment by Dave-Morton** [comment]
I just tested the multi-bot GUI and the dropdown list was properly filled with all 7 of my currently available chatbots, so that's something we need to look at here in a moment. First, let me explain how to access the "non-default" chatbot in the other GUI examples.

In order to be able to chat with another chatbot in any of the example GUI pages, all you need to do is specify the bot ID in the URL, like this:

`http://www.example.com/path/to/your/chatbot/?bot_id=2`

That will cause the GUI to use the chatbot with the ID of 2, rather than the default bot. You can also specify the conversation ID in the same way by using the URL variable `convo_id`, just like this example:

`http://www.example.com/path/to/your/chatbot/?bot_id=2&convo_id=Dave`

Here's a "real world" example URL that I could use on my system to illustrate:

`http://localhost/Program-O/gui/jquery/index.php?bot_id=3&convo_id=dave`

Now, as to the problem with the dropdown list not populating, I'll need some additional information, so if you could please read [This Wiki Entry](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) and provide the information listed there, it would go a long way toward helping me to help you. And please don't forget to include any error logs that may have been generated. they can help a lot. thanks.

**Comment by newbieh** [comment]
if there is a way to switch bot_id by keyword input?

**Comment by Dave-Morton** [comment]
No, there isn't, really. All chatbots are designed to be separate. there are ways to get around this, if you're experienced in AIML and JavaScript, but that's beyond the scope of the project.
