### ISSUE TITLE
How to make custom language for not English developers

### ISSUE THREAD

**Issue by cainconstantine** [Program-O/Program-O#198]
.po

**Comment by Dave-Morton** [comment]
Which language did you want to use?

**Comment by cainconstantine** [comment]
Chinese 
Can be zh-cn or zh-tw
I 've modified some .php strings to translate a lot
![prt sc](https://cloud.githubusercontent.com/assets/17424108/21577858/6c5c0a16-cfa5-11e6-9dc5-81bbb5e36a56.jpg)
Did u have an already translated patch?
This is my url : http://www.deityfile.com/chat/gui/jquery/

**Comment by patrickschur** [comment]
Currently there are no translation files. But I like the idea. @Dave-Morton what do you think?

**Comment by Dave-Morton** [comment]
While I think it's a great idea, I also know that it would be a *HUGE* amount of work, since the project was hard-coded as English. In order to accommodate such a change, practically every script in the project would have to be gone through, any English text replaced with a variable (most likely as part of a `$language` array), and language files created that would hold the text in whatever language is needed. As my college classes begin again on Monday, the 23rd of January (3 days from now), I won't have much time to implement such a change any time soon, but I encourage any interested parties to fork the project and formulate solutions of their own. If a solution is found that both works and passes dev team approval, I'm certain that it's inclusion in the project would be a benefit to all. :)

**Comment by patrickschur** [comment]
Challenge accepted. I'm working on it. :)

**Comment by Dave-Morton** [comment]
I'm not certain whether it's best to use an array or a PHP object to hold the language strings. Probably an array would be easiest to code, so perhaps it would be best to start there. I'm thinking of something along these lines:

```PHP
$lang = array(
    'botPersonality' => array( //corresponds to botpersonality.php
        'updateBot'   => array(   // corresponds to the function updateBot
            'success'    => 'Bot Personality Updated.',
            'error'        => 'Something went wrong! Affected rows = '
        )
    )
);
```

and so on. But this is just off the top of my head, and there may be a better way to do this.

**Comment by patrickschur** [comment]
I'll do my best. But first off I'm working on another project off my own. 
Do you really think to use a class for that? It's a kind of inconsistent. I mean the whole project is programmed functional, with a few exceptions. We should keep it. Also your approach looks at least not bad.

**Comment by Dave-Morton** [comment]
It was just a thought, is all. :)

**Comment by patrickschur** [comment]
It takes more time than I thought. Theres a lot of work. :(
So much hard-coded strings. My main problem are the template and javascript files.
We need to rewrite a lot.

**Comment by Dave-Morton** [comment]
That was kind of my point. I suggest breaking this down into smaller sections. Tackle the PHP scripts first, then we can deal with the HTML template and the JavaScript later.

**Comment by Dave-Morton** [comment]
Most likely, it would just be simpler to create a different HTML template file for each language. That way there's not as much to do with regards to replacing one set of text for another. Depending on how much language dependent text there is in the JS files, we may wish to consider doing the same for them, as well.

**Comment by patrickschur** [comment]
I had the same thoughts. But I don't like the idea of having multiple files, with almost identical content.

**Comment by patrickschur** [comment]
There are also issues with the script itself. For example when I rename the button "Save" in the installation script to "Installation", the script doesn't work anymore.

**Comment by Dave-Morton** [comment]
Can you post both the original code, and the modified code, so that I can see specifically what you're referring to?

**Comment by patrickschur** [comment]
When I try to translate the file `install.tpl.htm` at line 155 from:
```html
<input name="action" id="action" type="submit" value="Save">
```
to 
```html
<input name="action" id="action" type="submit" value="Speichern">
```
the installation script will not work. Which causes a problem in `install_programo.php` at line 98:
```php
$message = $action($page);
```
after the translation the code looks like this
```php
$message = Speichern($page); // instead of Save($page)
```
I hope it's clear.

**Comment by Dave-Morton** [comment]
That's because the name of that button is also the name of the function that it's calling in the script. Try this:

```php
<input type="hidden" name="action" value="Save">
<input id="action" type="submit" value="Speichern">
```

**Comment by Dave-Morton** [comment]
Something else that comes to mind is the question of how to choose the language to use for the install process, and thus, the rest of the usage of the script. I'm thinking that something along the lines of a selectbox at the very start of the install process that is populated by a list of template files in the various available languages in the templates folder, and I think that this should require a basic change to the folder structure of a portion of the project. Instead of storing the template files where they are, we should create a  folder named `lang`, and folders under that one with the name of the locale code (LCID) for each language, like this:

```
lang
    en-us
    en-gb
    de
    zh-cn
```

and so on. There would then need to be a "default" language (e.g. `en-us`) to start out with, which could then be altered within both the install script _and_ the admin script. This should not be set as a constant, however, as it would need be be flexible enough to change as desired. I think that it would probably be best to have a `lang` setting in the database that can be called upon, but set by a default value if it's not set in the DB. contact me via email and we can discuss details of this.

**Comment by Shaolinshifu** [comment]
Can you please guide me how to make voice enable with chatting like your demo site?

**Comment by cainconstantine** [comment]
it's textToSpeak in javascript
```
<script>
function speak(textToSpeak) {
		var u = new SpeechSynthesisUtterance();
		u.text = textToSpeak;    
		u.lang = 'en-us'; 
  		u.rate =0.9;  
  		speechSynthesis.speak(u);
} 
 	speak("Hello，my name is Eternal"); 
function sk() { 
 	$(document).ready(function() {
        setTimeout(function(){speak(spk.innerText);},1000); 
 	});
}  
</script>
```
```
<input type="submit" name="submit" id="submit" class="submit"  value="发送"  onclick="javascript:sk()"/>
```

**Comment by AlekzNet** [comment]
Another solution is to rewrite everything with a sort of a decorator. For example, this is how it's done in WordPress:

```php
<p class="no-comments"><?php _e( 'Comments are closed.', 'twentyfifteen' ); ?></p>
```

**Comment by Shaolinshifu** [comment]
Dear cainconstantine!
Still now i dont know what happen to my coding, I use same method like your guide above but nothing happen to my demo.
Can you take a look on my demo and help me?
http://gamethu.pro/chat/gui/jquery/

**Comment by cainconstantine** [comment]
Dear Shaolinshifu,
I've already seen your website and your code,it's good to hear the voice "hello,my name is eternal" when the website is loaded.You can modify it.
But when I chat with your bot , it doesn't speek.
So the problem is about words the bot says doens't transform into voice.
My design is give the `<div class="botsay">` an id,it will be `<div class="botsay" id="spk">`
Thats why I wrote spk.innertext in my js-part code.
You can also change its id and remmember to change ???.innertext
in code:
```
<div class="centerthis">
      <div class="rightside">
      <div class="manspeech">
        <div class="triangle-border bottom blue">
          <div class="botsay" id="spk">Absolutely.</div>
<!--HERE! I added an id in the div,its name should be the same as the id in <script>-->
        </div>
      </div>
      <div class="man"></div>
      </div>
      <div class="leftside">
      <div class="dogspeech">
        <div class="triangle-border-right bottom orange">
          <div class="usersay">fuck</div>
        </div>
      </div><br>
      <div class="dog"></div>
      </div>
    </div>
```
```
<script>
function speak(textToSpeak) {
		var u = new SpeechSynthesisUtterance();
		u.text = textToSpeak;    
		u.lang = 'en-us'; 
  		u.rate =0.9;  
  		speechSynthesis.speak(u);
} 
 	speak("Hello，my name is Eternal"); 
function sk() { 
 	$(document).ready(function() {
        setTimeout(function(){speak(spk.innerText);},1000); //HERE, that spk.innerText
 	});
}  
</script>
```
Do you understand?
By the way,if you want to play it on your mobile device ,your mobile language should be set into English,otherwise your bot won't speek.
In my case,I use iphone ios 10 and my system language is Chinese so that my bot didn't speek
But it will speak Chinese when I play this demo: http://www.deityfile.com/read/
You can change the language in `u.lang = 'en-us'; `,but I think AIML only support chatting in English-like language , isn't it?

**Comment by Dave-Morton** [comment]
@cainconstantine I'm sorry this issue got "left behind" for a while. Program O supports languages other than English, actually. In fact, it's been tested with Dutch, Chinese and German with great success, so if you have a web interface that allows speech for a given language, so long as the language setting for the interface matches the language used for the output the TTS should work. I think I'll see about adding a "Language" setting for the per-bot configuration so that this feature can be more easily used, but this will not be able to be implemented until a later version.

**Comment by Dave-Morton** [comment]
I've given this a bit of thought over the months, and I think that the easiest way to support languages other than US English would be to create a different HTML template file for each language, and set a variable in the config file during the install process to select the correct templates for the language. this is STILL a lot of work, as much of the text generated for the admin pages is still hard-coded, but it's doable. @patrickschur are you still working on this, by chance?

**Comment by Program-O** [comment]
this issue is closed.
The version 3 (which is soon to be released) admin area will support multiple languages.
If you would like to contribute to a chinese version of the admin area please get in touch and i will be happy to release an language file for you to translate
it would be amazing if you could help 😄 
Just send me a message on the project forum and i will get back to you
https://program-o.com/forum/categories/feature-requests
