### ISSUE TITLE
Config file editor is not working correctly

### ISSUE THREAD

**Issue by patrickschur** [Program-O/Program-O#211]
There is an issue with edit_config.php because the file config/config.template.php doesn't exists. 
Line 12:
```php
$contents = file_get_contents('../config/config.template.php');
```
I think it should be
```php
$contents = file_get_contents('../install/config.template.php');
```
or
```php
$contents = file_get_contents('../config/global_config.php');
```
But I have no idea what you have imagined with it. So please correct this.
I think that is also not intended:

![screenshot from 2017-01-05 18-42-55](https://cloud.githubusercontent.com/assets/18181635/21690987/03cbe3b0-d377-11e6-87f6-f50640b8aa01.png)

**Comment by Dave-Morton** [comment]
That particular editor was more or less experimental, and I never got around to doing much with it. This is mainly because potentially damaging results could come about if the user isn't careful about what their doing. As to the two proposed fixes, the second option is the correct one, with regard to which file to open. As for the memory limit portion, that's functionally been removed from use, so that entire section of code could be done away with. Program O now uses far less memory than it once did, so that portion of code is more or less analogous to a Human appendix.

**Comment by patrickschur** [comment]
So the file is useless and can be deleted?

**Comment by Dave-Morton** [comment]
I think that it deserves some attention, but in it's current form could potentially be dangerous to use. Delete it if you wish, but I'll keep a copy locally to work on at a later date.
