### ISSUE TITLE
convo id

### ISSUE THREAD

**Issue by rupesh1910** [Program-O/Program-O#215]
the convo id does not change once i close the browser and the convo id session does not get cleared

**Comment by Dave-Morton** [comment]
That's because the session is "timed", rather than a simple "disposable" session. If you want to make the session expire when you close your browser, you'll need to change the way the session cookie is set. I'm in the middle of heavy system maintenance on my development computer (which is where I keep the Program O project), so I'm unable to directly access the code to direct you where to make the necessary changes for altering the session behavior. If one of the other dev team members could assist with this, I'd appreciate it. :)

**Comment by rupesh1910** [comment]
can you give me hint where can i do that

**Comment by Dave-Morton** [comment]
That depends on which GUI interface you're using, as the cookie that controls the session is set within the code for each GUI. If you're using a "roll your own" interface, then it's up to you to set the cookie using one of several methods. I would have to know how your users are accessing the bot (and preferably be able to see the code, if it's not one of the currently supplied GUI templates) before I could advise you further. You could also look for the functions `setCookie()` or `session_set_cookie_params()` to see how the cookie is being set, and then modify the parameters from there.

**Comment by patrickschur** [comment]
It also depends on your browser settings. For example my browser removes all cookies after closing the browser.

**Comment by AlekzNet** [comment]
Personally, I find it a useful feature. You can continue your conversation from the moment you left it.

**Comment by Dave-Morton** [comment]
I agree. However, the cookie is set in far too many places at present. I think that a small "stub" script would be a good idea to have that could be called by any script that makes use of sessions. This may take a while for me to implement, however, with my new classes starting up in a few days. But I'll see about fitting it in somehow. :)

**Comment by rupesh1910** [comment]
Hi as i am using gui/jquery ui. i have just changed the design of it.

**Comment by rupesh1910** [comment]
HI Dave-Morton like you said for each gui there is setcookie. but i cant find so that i can delete to convo_id.

**Comment by Program-O** [comment]
this thread is over 30 days old which no further input am closing.
please get in touch if still no resolution
