### ISSUE TITLE
[SOLVED] Installation problem

### ISSUE THREAD

**Issue by xagon** [Program-O/Program-O#217]
Hi.
I'm having a big problem installing Program-o. Here's how I configured my MySQL.

![adf](http://bit.ly/2jVK1SR)

And my answer, after fill the form is **"
Cannot connect to the database! SQLSTATE[HY000] [1045] Access denied for user 'programo'@'localhost' (using password: YES)"**

**Comment by Dave-Morton** [comment]
A bit more information is needed in order for me to be able to assist. Please read [this wiki entry](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) on what information to provide. Then we can make some progress. Thanks.

BTW, I noticed that your image link was broken because the URL was too long to fit without splitting into two lines, so I took the opportunity to create a bit.ly linkto replace it and edited your post accordingly.

**Comment by Dave-Morton** [comment]
Also, are you connecting to localhost in your connection credentials? If not, then the 'localhost' setting in your grant table needs to be altered to `%` to accommodate a remote connection.

**Comment by xagon** [comment]
[Solved] there was an error in the MySQL installation
Thanks for your help.

**Comment by Dave-Morton** [comment]
No problem. Happy to assist.
