### ISSUE TITLE
AIML issue with <srai> and <star index="n">

### ISSUE THREAD

**Issue by enriquo** [Program-O/Program-O#222]
```
<category>
	<pattern>* SONO *</pattern>
        <template><srai>I AM<star index="2"/></srai></template>
</category>
```
Why the input "HELLO, I AM XAGON" sets the <star index="2"/> to "HELLO"? I tried testing using <star/> with and without the index property OUTSIDE the SRAI tag and all worked perfectly, so <star/> returns the first * and <star index="2" /> return the second *. But how can I solve this? Is a problem wit the Program-O core?

**Comment by patrickschur** [comment]
Do you have the lastest version of Program-O? A blank space is also missing, write:
```xml
<template><srai>I AM <star index="2"/></srai></template>
```

**Comment by Dave-Morton** [comment]
In order to best help you with this issue, a bit more information is necessary. Please read (this wiki entry)[https://github.com/Program-O/Program-O/wiki/Reporting-Issues] to learn what information is needed. You might also wish to edit your AIML category to fix a minor bug that is has. You seem to be missing a space in your `<template>` tag. Perhaps this might be a part of the problem?

```xml
<category>
	<pattern>* SONO *</pattern>
        <template><srai>I AM <star index="2"/></srai></template><!-- please note the space between the word AM and the SRAI tag -->
</category>
```

**Comment by xagon** [comment]
Hi Dave Morton, I want to take the opportunity to say that you made a really good job in my opinion, I read some of your forum entries and some of your work.

Now, 'bout the problem: yeah the space was missing, thanks. But the problem hasn't gone away, I still have <star index="1" /> equal to <star index="2" /> **INSIDE** the <srai> tag. Can it be a problem of the ProgramO core? Or it's something that cannot be done?

I will try to explain better what I thought and please forgive me for my bad english.
_What I think_ that the ProgramO Core is doing is taking my AIML and converting it to a [deterministic](https://en.wikipedia.org/wiki/Deterministic_finite_automaton) [Mealy machine](https://en.wikipedia.org/wiki/Mealy_machine). But if I have multiple * and one of them is at the start of the <pattern>, how can ProgramO can build a deterministic machine? It will obviously result as a NON-deterministic machine, because how ProgramO can know how to recognize the * pattern that is before my "**SONO**"? This is just a thought, and actually the bot is working with this configuration and it's possible to recognize <star index="1" /> equal to <star index="2" /> **OUTSIDE** the <srai> tag.

I dunno what to do.

**Comment by AlekzNet** [comment]
It might be related to https://github.com/Program-O/Program-O/issues/172, which was fixed by @patrickschur, but not made it yet to the dev repository.

**Comment by enriquo** [comment]
Yeah, it's absolutely related. I'm tuned to the /dev/ repo hoping soon I will see the update. Thanks @Dave-Morton @AlekzNet

**Comment by Dave-Morton** [comment]
I just reviewed the changes in Pull Request #223 and it looks like it may also address this issue as well. Please download the latest version from the `DEV` branch and try it out. Let us know how it goes.

**Comment by AlekzNet** [comment]
Looks excellent so far! Thanks @patrickschur!

**Comment by patrickschur** [comment]
I tested it so far and forgot to reference this issue.

**Comment by enriquo** [comment]
Thank you, now everything is working well.

**Comment by AlekzNet** [comment]
Closing.
