### ISSUE TITLE
aiml files not working

### ISSUE THREAD

**Issue by harroman** [Program-O/Program-O#230]
I have a new installation and everything seems to be working except that when I try to upload any of the provided aiml files I get numerous errors. 
default.aiml 17 errors
ai.aiml 13 errors
alice.aiml 18 errors
etc

For example, these are from the atomic.aiml file

Error 1839: Element '<a>', attribute 'target': [facet 'pattern'] The value '_new' is not
accepted by the pattern '_(blank|self|parent|top)|[A-Za-z]\c*'. on line 2,745.
Error 1824: Element '<a>', attribute 'target': '_new' is not a valid value of the atomic
type 'FrameTarget'. on line 2,745.
Error 1843: Element '<random>': Character content other than whitespace is not allowed
because the content type is 'element-only'. on line 3,398.

Any ideas would be gratefully accepted
John

**Comment by Dave-Morton** [comment]
It appears that the AIML files that you've tried to upload might be from among some of the older versions that contain either encoding errors or syntax errors. Since Program O doesn't come with AIML files (this is intentionally left to the botmaster to obtain, as there are so many versions available to use), it's best to try to get versions that have had these errors corrected. I mention a version of the ALICE AIML set that has had the corrections made to them in issue #186 - but rather than having to read through the entire issue to find the link, here it is:

http://www.geekcavecreations.com/Downloads/aiml.zip

Try uploading these AIML files and see if that takes care of the problem.

**Comment by Shaolinshifu** [comment]
![image](https://cloud.githubusercontent.com/assets/25561960/23005906/6887008e-f431-11e6-9105-fde85d9369b8.png)
I have same problem with harroman.
I try to download your new AIML Dave-Morton from your website. But I still got this problem.
From version 2.6.2 I not met this problem when I upload my AIML but since version 2.6.3 Master and 2.6.4 DEV, alot of Alice AIML cant work with these version.
I guess the problem happen when using tag <a href>

**Comment by harroman** [comment]
Hi Dave
Thanks a lot for the quick reply. I have tried some of the files from the link you gave and they are a lot better. Some are fine straight away and some have a few errors but not as many as before. The good thing is that it has forced me to learn a lot about aiml syntax so I have managed to correct any problems I have found. 
Keep up the good work!
Thanks again
John

**Comment by Dave-Morton** [comment]
@harroman Happy to help, John. Please let us know how you make out with your chatbots.

@Shaolinshifu That you're seeing these validation failures from version 2.6.3 on isn't surprising. It was then that we added more strict validation of the AIML files to address other issues that were occurring due to invalid AIML files. At that same time we also added improved validation error messages in order to assist botmasters in diagnosing and correcting the files that fail validation. For example, in the screenshot you've provided, the file ai.aiml had failed validation because on line 161 of that file there's an HTML anchor tag (`<a>`) that contains the attribute `target` that contains the value of "_new". According to the [AIML 1.0 Specification](http://www.alicebot.org/TR/2001/WD-aiml-1.0.1-20011018-005.html) HTML anchor tags (`<a>`) are allowed, but the [DTD file] (admin/aiml.dtd) is very restrictive as to the content of these anchor tags and their [allowed attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target). As such, the script is actually doing it's job, and is therefore not experiencing a bug.

At this point you have two options here. you can either:
- use the validation error messages to troubleshoot and repair the AIML files that don't pass validation, 
- Find other AIML files that have already been corrected, or:
- skip validation altogether by checking the checkbox labelled "Skip AIML Validation for this file" (**NOT** recommended).

**Comment by harroman** [comment]
Hi Dave
Doing really well so far with entering my questions (about Tai Chi), but I
have come across a problem. For some of my patterns I have put a * on the
end, (eg * TAI CHI * FIT * ) but then if I ask a question without a word
after FIT it doesn't answer. To make it work I have to do another pattern
without a * on the end and use srai to connect to the first one. Is there
not a wild card which accepts a word if you have one, but is happy if you
don't have one, or do you have to match a word of at least 1 character.
Hope this makes sense

Thanks
John

**Comment by Dave-Morton** [comment]
If you could post some example AIML that would help, but I suspect it's likely that you may be misunderstanding how the `*` wildcard works. In the AIML 1.0 specification, both the `*` and `_` wildcards _REQUIRE_ something to match against. For example `<pattern>* TAI CHI * FIT *</pattern>` will match "How can Tai Chi help me to keep fit with a busy schedule?", but it will **not** match "How can Tai Chi help me to keep fit?" In order to match the second question that I've posted, you need another AIML category with this pattern: 
`<pattern>* TAI CHI * FIT</pattern>`
Try creating a new category that contains this pattern, and see if that helps.

**Comment by harroman** [comment]
Thanks a lot.
You've confirmed exactly what I thought might be the case.
It's very interesting trying to come up with patterns to cover what people
might ask. And I imagine once I get to grips with some of the more
complicated pattern structures it will be even more interesting.

Thanks
John

**Comment by Dave-Morton** [comment]
Glad to help, John. Let me know if there's anything else you need.

**Comment by yogirajesh19** [comment]
I am not understanding what this error means .Please help
1st.aiml (char 1)
stage: parsing - likely at the beginning of the file
[in Sax parser] parse of # failed filename cache/managea/files/86/862676ff9d9cdde953eba2c54dd9f9e7cad82b41, position near character 1

**Comment by patrickschur** [comment]
@yogirajesh19 You have an error in your AIML file. Likely the doctype is wrong.
