### ISSUE TITLE
Endpoints + Misspells issues

### ISSUE THREAD

**Issue by brunogpires** [Program-O/Program-O#233]
Hello there.

This is my first contact with the community, and i'd like to thank everyone who worked in this awesome tool. I've been working with program-o by the last 2 weeks, and im diving into some issues which i couldn't find a satisfatory answer.

The most annoyant one  is related to endpoints and misspells. 

Let's say i have added a misspell for the word 'you':
'u' => 'you'

If the user input something like 'who are u?', the system will not fix the misspell because of the '?', and before adding a workaround fix in my application, i'd like to know if is this a known bug or a known behaviour which im not familiar with?

Thanks for your time and sorry if this is some kind of silly question.

**Comment by Dave-Morton** [comment]
@brunogpires Hi and welcome!

First off, don't worry about whether your question or issue is "silly". My father always said, "the only stupid question is the one never asked", and I believe that completely, so you have nothing to worry about in that regard.

Secondly, I think a bit more information would be helpful here. Kindly read [this wiki post](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to see what sort of information to provide to help us to help you. this information will help us by making sure that we're using the same OS, server software, PHP version and version/branch of Program O, so that we can test "apples to apples", and are more likely to see what you see.

~~From your post, I'm getting the sense that "who are u?" fails to correct the misspelling, but "who are u" (no question mark) works?~~ Never mind. I just tried this in my latest version, and it's functioning exactly as I described, where that question mark seems to prevent the spelling correction to occur. This is, indeed, a bug. I don't have time right now to work on a fix for it (school this semester is far more challenging than I had anticipated), but I'll try to make time this coming weekend.

**Comment by brunogpires** [comment]
Thank you @Dave-Morton for your prompt reply, and @patrickschur for the fix!

From what i see here, Patrick provided the real fix for the issue, but it doesn't seem to be applied to the master yet. I'd like to know how do you guys plan merges or releases?

And i hope i can join your contributor's team aswell at some point.

**Comment by Dave-Morton** [comment]
We (read: I, usually) merge the branches only after it's most recent code (additions and fixes both) have been tested enough to be considered "stable". This process can take a while at times, because I don't always have enough time to stay on top of things here; but I do my best. :) I'll be looking at merging the current `DEV` branch into `MASTER` this weekend.
