### ISSUE TITLE
Help with wildcards and some THAT functionality

### ISSUE THREAD

**Issue by hesomWela** [Program-O/Program-O#249]
Hello,

I am trying to create a proof-of-concept using the program-o tool and I am running into an issue with my AIML. I have attached what I have so far and its not uploading through the admin portal, even though it says it was successfully uploaded.

1. It look like my first patten is causing some of the problems. I am trying to use a * wildcard and then re-use that variable in the template. 

2. for the THAT nodes, it looks like I have to remove everything that is not a letter or a number for it to work. Is that the norm?

Note: I had to change the file from .aiml extension to .txt to attach.

thanks
[hesom.txt](https://github.com/Program-O/Program-O/files/863442/hesom.txt)

**Comment by Dave-Morton** [comment]
Part of the problem that I'm seeing can be illustrated with the following code:

`<pattern>how much did I spend on * last month?</pattern>`

There are several "issues" with this code, though one is not important. The first problem, and the one that breaks things, is that you have punctuation in your code there. __only letters, numbers, spaces or wildcard characters__ are allowed within AIML pattern-side tags (e.g. `<pattern>`, `<that>`, and `<topic>` tags). things like periods, commas, question marks (as is the case above) do not belong within these tags, and will seem to "break" things. What's really happening is that when the user enters text into the interface, their text is stripped of all punctuation and then tested, while the patterns being tested against still have the punctuation in place, so there will never be a match. The [AIML specification](http://www.alicebot.org/TR/2011/) spells out what exactly can be placed within pattern-side elements. It's a rather technical document, but it would benefit you greatly to study and understand the document before trying to create your own AIML files.

the second "problem" is that the text within all pattern-side AIML elements ___SHOULD___ be in all uppercase. this is a "best practice" thing, rather than a hard and fast rule, but if you share your AIML files with other people who author AIML, they're going to probably give you grief over lowercase words in patterns. Just sayin'.

The third thing I see that will cause you grief is that your `<that>` tags are __WAY__ too specific. You can use wildcards (mainly `*`) to remove unnecessary text from those tags, but be careful that you don't remove _too_ much text, making them too general.

Also, in your AIML you're asking questions that are __NOT__ yes or no questions, yet expecting either a yes or a no for a response. Take a close look at your second AIML category for an example of this. You'll never get expected results that way. I suggest to all of my students that they get a partner, and have a conversation about whatever they want to create AIML files about, then log every bit of the conversation and use that as a generic template for how to write the AIML files they need, repeating the process several (to dozens) of times, never using the same wording that they had before with their statements. This is a time consuming, tedious activity, but well worth the effort, because it makes for some really well written AIML files. Something to consider, at least.

**Comment by hesomWela** [comment]
@Dave-Morton Thank you very much!
