### ISSUE TITLE
Conflicting AIML patterns

### ISSUE THREAD

**Issue by ZastieX** [Program-O/Program-O#264]
Hi everyone, I have a simple question regarding AIML.
I found in default.aiml and learn.aiml (I get from other site) an exact same pattern: * IS *
However both patterns have different templates.
My question is, which one is going to be executed first?

*ps :I've tried several times, and I found that it's just randomly chosen.
Thank you

**Comment by Dave-Morton** [comment]
That's because if there are two  or more AIML categories that generate the same score (long explanation), Program O randomly picks between them.
Were working on an option to be able to use either a randomly picked category (what happens now), choose the _first_ entry in the stack, or the _most recent_ entry. this is still in development, but it seems to work. We don't have an option to change it in the admin yet, so the change needs to be made manually in `global_config.php`. All of this is currently available in the `DEV` branch if you want to check it out.

**Comment by ZastieX** [comment]
Thanks for your reply, Dave.
I decided to remove the conflicting AIML. But then I got another problem which is actually not related to AIML conflict.
The problem is: I used learn.aiml which purpose is to teach the bot from user's input. It contains <learn> and <eval> tags. I tried to teach the bot, and asked it the question and it can answer. However after I closed my browser (session ends), the bot couldn't answer the question anymore. I've checked that the knowledge is stored in aiml_userdefined table. 
Is there any way to solve this?
Thank you

**Comment by Dave-Morton** [comment]
If the new AIML category created is in the aiml_userdefined table, it should be available to the same user, but only if there is no AIML category with the same `<pattern>` in the regular aiml table. This is a bit of a design flaw, I'm afraid, but one that would require a complete redesign of the SQL query that looks for patterns to match. As a result, it's been assigned a pretty low priority. there are plans to address this in the next major version, but that's still a ways off.
