### ISSUE TITLE
Add AIML File Name in API 

### ISSUE THREAD

**Issue by CFlanc** [Program-O/Program-O#268]
Is there anyway to add more info about the response of bot in API
like the aiml file the response was generated from.
current category or topic i just need more info in API

**Comment by Dave-Morton** [comment]
Something like that is certainly possible, but it would take a redesign of the core code to add the information. Can you provide for us the sort of other things that you would like to see as output from the API?

**Comment by CFlanc** [comment]
Something That is Very Easy To Implement 
Maybe Category, Topic, Or AIML file Itself

**Comment by Dave-Morton** [comment]
Basically, *none* of that would be particularly easy to implement, because none of that information is collected during the process of selecting and parsing the response. So basically, during the search process, all of the relevant information that isn't currently being collected would need to gathered, then stored in some manner that is easily retrieved. Then that retrieved data would need to be added to the JSON string that is returned by the API. As I said, it's certainly possible, but it would take some effort. Currently, I'm a week out from my finals in college, and as such am buried in academics. Once summer break hits, near the first part of June, I should have time to look into this. Till then, please give us a very specific list of what you would like to see as part of the API's output. That will help a lot.

**Comment by CFlanc** [comment]
Category, Topic, That, Pattern, Predicates OR AIML File The More We Can Get The Better It Would Be Since We Are Going to Implement It Why Can We Get all

**Comment by Dave-Morton** [comment]
Ok, the recent push I did adds a "data" array to the JSON object that the API returns. You can access it as response.data.{insert property name here} - the properties are:
+ aiml_id: the ID of the AIML category in the database
+ pattern: The `pattern` of the AIML category selected
+ thatpattern: The `that` of the AIML category selected
+ topic: The `topic` of the AIML category selected
+ score: the score awarded
+ track_score: The description of attributes that earned the aforementioned score*
+ filename: The name of the AIML file that contains the selected category

_*_ This is a bit tricky to explain, up until you see what's there. Just have a look at the value and it should become clear. If not, just ask about it. :)

An example of the new JSON output is below:

```Javascript
{"convo_id":"eadpiltbek9vt483jkmjb35sv3","usersay":"test","botsay":"This is just a test.","data":{"aiml_id":"468730","pattern":"TEST","thatpattern":"","topic":"","filename":"atomic.aiml","score":260,"track_score":"current bot, no topic to match, no thatpattern to match, direct pattern match, direct word match: test"}}
```

**Comment by CFlanc** [comment]
Thats Awesome!
