### ISSUE TITLE
FEATURE: Batch Upload AIML Files

### ISSUE THREAD

**Issue by KgotsoK** [Program-O/Program-O#272]
It would be a nice feature if we could batch upload AIML Files. I have a whole list of them that I use to administer bots but it always takes longer than it should to upload the files.

Can we have this feature?

**Comment by patrickschur** [comment]
What exactly do you mean with "batch" uploaded AIML files? Combine two or more AIML files to one? If yes, you can also upload a `.zip` file.

**Comment by Dave-Morton** [comment]
That has actually been a feature for several years now. If you have multiple AIML files to upload you can simply place them all in a ZIP archive and upload that archive using the Upload AIML interface in the admin pages. Each file will then be validated and added to the chatbot's database (provided it passes validation, of course!).

**Comment by KgotsoK** [comment]
Actually had no idea - I just had multiple AIML files i use to initialise bots (Base vocab kinda stuff). I was uploading them sequentially, which can take time.

Thanks @Dave-Morton @patrickschur

**Comment by KgotsoK** [comment]
And by Batch upload I meant the dialog used to select the AIML (or zip file) should allow a user to select multiple files in the file-selection dialog that pops up. 

But the zip feature takes care of the multiple AIML file upload issue.

**Comment by Dave-Morton** [comment]
We'll look into adding the ability to upload multiple individual AIML files, but this won't happen right away. There are other things that have a higher priority right now. :)

**Comment by alianrkeasan** [comment]
Hey everybody. Did you succeed on uploading several aiml files on a zip package? I could not.

**Comment by alianrkeasan** [comment]
Hey everybody. Did you succeed on uploading several aiml files in a zip package? I could not.

This is the errors


Fatal Error
9: Input is not proper UTF-8, indicate encoding ! Bytes: 0xA9 0xB8 0x28
0xDF on line 2.
Fatal Error 9: PCDATA invalid Char value 14 on line 2.
Fatal Error 9: PCDATA invalid Char value 22 on line 2.
Fatal Error 9: PCDATA invalid Char value 21 on line 2.

etc...

Can you help me on batch upload aiml files on my bot?

**Comment by Dave-Morton** [comment]
That's a problem with one of the AIML files in the zip archive being invalid XML. The upload page of the admin has links to both an XML validator and an AIML validator that you can use to make sure the files you're uploading are valid. The AIML validator will give specific details of where the XML errors, and on which line of the file that's failing validation. This makes it very easy to determine what's wrong so that it can be corrected.

**Comment by alianrkeasan** [comment]
So I'll have to upload the files one by one?

**Comment by Dave-Morton** [comment]
No, just extract the files from the archive, validate each one individually (the validator isn't designed to validate files within an archive), fix the problem(s) in the files that fail validation, update the zip file with the corrected files, then upload the zip file. Yes, it's more work than individually uploading each AIML file, but once you complete the process you won't have to do it again for that zip file.

I should also point out that the upload script will point out exactly which files within the archive failed validation so you'll only have to extract and fix those files, rather than the entire archive.

**Comment by Sjoerd22** [comment]
Can't someone validate the files and update the archive ? Please ?

**Comment by Dave-Morton** [comment]
Program O doesn't ship with any AIML files, and never has. This has always been intended to be up to the individual botmaster to handle. If you navigate to [my website's Downloads page](http://www.geekcavecreations.com/?downloads) you'lll find some AIML file zip archives that will pass validation.

**Comment by Program-O** [comment]
closing as this is an AIML issue not a program o issue
