### ISSUE TITLE
Integrationso with Android app

### ISSUE THREAD

**Issue by sevenOneHero** [Program-O/Program-O#278]
Hey guys, app for programing chat bots is on Play Store for android, there you can chat with the three bots Shakespeare, chat Mundon and the programobot. I am willing to add more bots in it , so if you have a working functional bot and apurva access is provided by you , I can add your chat boy within the app

https://play.google.com/store/apps/details?id=com.chaat0

**Comment by sevenOneHero** [comment]
Sorry for the spelling mistakes

**Comment by patrickschur** [comment]
Please no ads!

**Comment by Dave-Morton** [comment]
While I agree that in general ads here are not a good thing, I actually don't see a problem with that one, mainly because it's more along the lines of showing us how they integrated Program O into something that they've made, rather than to try to sell something, and looking at the link itself, I don't see any sort of price or cost involved, so I would be willing to allow it. things that don't relate to Program O, or things that are blatantly trying to _sell_ something are another story, however.

**Comment by patrickschur** [comment]
@Dave-Morton He tries to win users for his platform. For me this is an ad. It does not belong here.

Insteadof writing this here in the issues he should use a forum like chatbots.org or something like that.
