### ISSUE TITLE
php memory limit reached

### ISSUE THREAD

**Issue by rwaters71** [Program-O/Program-O#279]
I am playing with Program-O and about 100k rows in the aiml table (~20MB). 
While testing, a simple direct match of "WHAT IS A ..............."  was instead forwarded to a  "WHAT IS *" rule, Looking through the debug logs I discovered --> "memory limit exceeded".
Here are the system specs: Program O version: 2.6.5. Server:  Apache 2.4, PHP 5.6.15, MariaDB 10.0.21, Fedora Core Linux. (default memory limit under PHP 5.6 is 128MB)

Looking at the global_config.php, seems that the program defaults to half the allowed memory from php.ini?
```php
$mem_limit *= 0.5; // half of the memory limit set by PHP
```
In my case, simply doubling it back to the php.ini allowed size solved the issue with the direct match.
I just thought I'd share, maybe something to consider for future versions?

I realize it was a rather broad match, but still, RAM is cheap these days :)
```
[find_aiml.php][find_aiml_matches][1127]
Current operation exceeds memory threshold. Aborting data retrieval. 
```

**Comment by Dave-Morton** [comment]
Generally speaking, if Program O is taking up more than half of the memory allocated to PHP, even with 100k categories in the database, something is amiss, considering that the code has been redesigned in the past to reduce the amount of memory required. In fact, it uses so much less memory than it used to that I've been seriously considering removing the memory management code, so to see this issue now begs the question of what version of Program O you might be using. If it's a version older than 2.4.6 you may wish to update to the latest version. If it's newer than that then I'd like to know your server's specs so that I can do some testing.

**Comment by rwaters71** [comment]
updated my original post with the server specs, I will be glad to provide any information you need and web access for you look around.  Thanks for the help.

**Comment by patrickschur** [comment]
I agree with you that the line should be removed. So that Program-O can use more memory.

But RAM (DDR4) is definitely not cheap these days. It's expensive like never before. It costs almost twice as much as a year ago.

**Comment by Program-O** [comment]
closing over 30 days old and no further input
