### ISSUE TITLE
Something went wrong error

### ISSUE THREAD

**Issue by jamieduk** [Program-O/Program-O#293]
Something went wrong error but it does not say what, i have removed all db enteries and reinstalled and still it fails i have uploaded aim file like i was told and also permissions are all correct!

also get this error 

No AIML category found. This is a Default Response.

in 

gui/plain/index.php

page and dont know how to fix it! :/

**Comment by Dave-Morton** [comment]
The "No AIML category found" bit is the default response given when nothing else matches. This is generally because the script couldn't find any matching AIML categories to parse. Either you have no "default" AIML category (one with either * or RANDOM PICKUP LINE for the PATTERN), or you have no AIML categories at all. 
Tell me please, is your chatbot available on the web, or is it strictly local to your computer?

**Comment by Program-O** [comment]
closing not an error
this will be fixed by adding a default catch all response so when no category its matched it will reply with a response instead of the default response "No AIML category found. This is a Default Response."
