### ISSUE TITLE
Fresh Install Error

### ISSUE THREAD

**Issue by hanoncs** [Program-O/Program-O#301]
Just installed fresh. Everything went good, except I was getting an error. I checked the global_config.php that gets generated. There was an error.

`define('_SESSION_PATH_', _ADMIN_PATH_ . 'ses_a9c01c88899c7f33475658f3\' . $path_separator);`

See the backslash in the ses_a9c01c88899c7f33475658f3 string? Issue wherever this gets generated.

**Comment by Dave-Morton** [comment]
This issue has been reported (issues #255 and #275) and corrected (https://github.com/Program-O/Program-O/commit/7f37d4726b0405e7b22dce270bee2f10858f91c3) already. Please download the latest version and try again.

**Comment by hanoncs** [comment]
Hmm I don't see anyone mentioning anything about the _SESSION_PATH_ in either of those issues, but your the boss.

**Comment by Dave-Morton** [comment]
Take a look at the notes for that commit. It's item 1.

**Comment by patrickschur** [comment]
@Dave-Morton The defined constant IS_WINDOWS is never used... Are you sure this issue has been fixed?

**Comment by hanoncs** [comment]
@Dave-Morton I downloaded/installed your master yesterday and had this issue. This fix was supposed to be that version I used? 2.6.5

**Comment by patrickschur** [comment]
@hanoncs The branch its'n merged yet into the master. So, you have to use the dev branch. I doubt this will work however give it a try.

**Comment by hanoncs** [comment]
@patrickschur thanks, I fixed the PHP issues on my master. Just reporting the issue.

**Comment by Dave-Morton** [comment]
@patrickschur That particular constant isn't actually part of the backslash issue, so is kind of irrelevant. But you're right in that `IS_WINDOWS` is no longer used. It's a holdover from when certain accommodations had to be made for Win32 operating systems. I'll see about removing it at some future point.

@hanoncs I should have mentioned that the issue was corrected in the `DEV` branch. Sorry about that. We're still testing the `DEV` branch to make sure all of the bugs that it has/had have been corrected before we merge it into the `MASTER` branch.
