### ISSUE TITLE
Unable to upload AIML zip on admin page

### ISSUE THREAD

**Issue by DarkTetsuo** [Program-O/Program-O#303]
When I click upload after selecting my alice aiml zip, I get taken to an error 500 page in chrome. I have been trying for a few hours now to try to fix it and I can't seem to get it. Here is the following log from admin.error.log:

[05-Jul-2017 16:20:53 America/New_York] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to handle_exceptions() must be an instance of Exception, instance of Error given in /var/www/html/testing.lan/admin/index.php:533
Stack trace:
#0 [internal function]: handle_exceptions(Object(Error))
#1 {main}
  thrown in /var/www/html/testing.lan/admin/index.php on line 533

**Comment by Dave-Morton** [comment]
We're sorry you're experiencing difficulties, and we'd like to help you with this, but we need some more information in order to be able to do so. Please read [this post](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) for details of what sort of information we need, and how to obtain it. Then post back with that information and we can better assist you.

**Comment by DarkTetsuo** [comment]
It is installed on my home server which is only accessible on my local network.  The server is running Ubuntu 16.04, nginx 1.10.3, PHP 7.0, MySQL 14.14. I am accessing it using Chrome 59 on Windows 10.
If I left anything out please let me know.

**Comment by Dave-Morton** [comment]
you left out the version of Program O, and whether you got it from the `MASTER` or `DEV` branches, which is the most important thing. There have been a great many new features, bug fixes, new bugs and other things over the past couple of weeks, so it's best to have the most recent version from either branch, if possible. We just need to know which. :)

**Comment by DarkTetsuo** [comment]
Whoops sorry! I am on version 2.6.5 from the MASTER branch

**Comment by DarkTetsuo** [comment]
Quick update. I found that I got a more descriptive error after installing php-mysql, php7.0-mbstring, php7.0-zip, and php7.0-xml . For some reason they weren't included in the regular PHP install. Now When I click upload I get "413 Request Entity Too Large." I know there is a limit on the file size but it is a 1503KB zip so it should work. Does this error make any more sense?

**Comment by DarkTetsuo** [comment]
I followed this guide here:
https://stackoverflow.com/questions/24306335/413-request-entity-too-large-file-upload-issue
to increase the max upload and that did the trick. It all appears to be working now!

**Comment by Dave-Morton** [comment]
I invite you to try out the `DEV` branch. there are a lot more features and bug fixes in that version, and I'm almost ready to merge it into the `MASTER` branch. I think you'll like the changes.

Be advised, though, that if you go with the `DEV` branch, you'll need to do a full install of Program O since there have been changes made to the structure of the database.

**Comment by DarkTetsuo** [comment]
Any idea when version 3 will be getting released? If not for a while may I suggest it have a beta release early? I cant wait to get a hold of that new API.

**Comment by Program-O** [comment]
Hi it will probably we a few months yet
I dont think we will be doing beta releases as it will be open source so in that sense it's either released or it is not but
If you keep an eye on the forum we will post updates over there
https://program-o.com/forum/
thanks for your support :D
