### ISSUE TITLE
Install program o on OS Sierra and XAMPP

### ISSUE THREAD

**Issue by ALAxHxC** [Program-O/Program-O#305]
Hi im trying to install program on OS Sierra and XAMPP, https://github.com/Program-O/Program-O but when I execute install show me this errors:

The config folder cannot be written to, or does not exist. Please correct this before you continue.

The debug folder cannot be written to, or does not exist. Please correct this before you continue.

The logs folder cannot be written to, or does not exist. Please correct this before you continue.

But I add the permissions in:
(see the image)
https://stackoverflow.com/questions/45104839/install-oprogram-chatboot-on-os-sierra-and-xampp

What im doing wrong?

**Comment by Dave-Morton** [comment]
You may not be doing anything wrong at all, actually. If you've downloaded from the `MASTER` branch it's possible that the permissions of those folders could be correct, but still not be writable because they're not "owned" by the correct user/group. I'm guessing that by "OS Sierra", you mean "OSX Sierra", which is a Mac OS, and I don't have a Mac to test on, but like most other *nix flavors, should have the `whoami` command. that command should tell you which user/group both your terminal and web server are running as, and you should be able to test that easily enough. From the image you posted on StackOverflow, I'd say that your terminal is running as 'admin', but you need to check what your web server is running as. [This StackOverflow question](https://stackoverflow.com/questions/28548743/php-get-current-user-vs-execwhoami) best describes the process of checking that. the accepted answer is fairly detailed, and should explain not only how to check to see what the web server (and by extension, PHP) is running as, but also what to set the permissions to (which should __NEVER__ be 777).

It's also possible that the function that checks to see if the folders are writable may be returning "false failures", meaning that the folders may well be writable, but the script's test may be failing to properly detect that. since I have no means to verify this (as I have no Mac system to test against), this remains a slim, but real, possibility.

A possible option may be to try downloading Program O from the `DEV` branch, which uses a different method for checking whether the folders in question are writable, and may prevent "false failure" results.

**Comment by Dave-Morton** [comment]
I take it from your closing the issue that you were able to resolve the issue? If so, please let us know what you did to do so. It may help others in the future.
