### ISSUE TITLE
Problem with aiml files

### ISSUE THREAD

**Issue by agliptis** [Program-O/Program-O#306]
Hello i try to upload aiml files but i have this picture.
![screenshot 2017-07-14 21 23 37](https://user-images.githubusercontent.com/30183333/28225322-f52d4e94-68da-11e7-8f29-9d4ac2c48f48.png)
Then t tried to go here http://www.geekcavecreations.com/?downloads (i read issues from other users) but i cant download the Unicode_ALICE_AIML.zip file. I have this picture:
![screenshot 2017-07-14 21 30 13 1](https://user-images.githubusercontent.com/30183333/28225559-ccbab0b8-68db-11e7-9100-8420319b6c7e.png)
Could you help me please? Thank you vety much!

**Comment by Dave-Morton** [comment]
Well, THAT seems broken. I'll have to look into my website. In the meantime, I'm assuming that you downloaded Program O from the `MASTER` branch, due to the type of error message the upload script produced. There have been some pretty major improvements to the upload script that make it easier to understand why certain AIML files failed validation, as well as an option to skip validation altogether (though this is really NOT recommended).

I've brought back a temporary downloads page [here](http://www.geekcavecreations.com/Downloads/) that will allow you to download the file. In fact, there are a few AIML file archives on that page, not just the Unicode version.

**Comment by agliptis** [comment]
Thank u a lot for the quick response! Well, i updated to this: Current Local Version: 2.6.5, Current GitHub Version: 2.6.5, Current Branch: Master, i used aiml_corrected file. Ihave this picture know:
![screenshot 2017-07-15 19 45 01](https://user-images.githubusercontent.com/30183333/28241175-0d45e33e-6998-11e7-898b-ddbab2b05efe.png)
I also used all other aiml files, but i had more errors.

**Comment by patrickschur** [comment]
That's because the AIML file is wrong encoded or contains illegal elements/characters.
Which AIML files do you use? Maybe it's because you are russian. We had a similiar issue before with a russian guy. The files have to be UTF-8 but russia use Cryllic as encoding. :)

**Comment by Dave-Morton** [comment]
I'm assuming that this has been resolved, since we've not heard back? If you're still having trouble, please open a new issue so we can get it handled for you. Thanks.
