### ISSUE TITLE
CSRF failure!

### ISSUE THREAD

**Issue by AaronZhangL** [Program-O/Program-O#323]
I got [CSRF failure!] message whe I try to access the page http://xxxx/Program-O/index.php
How to fix it?

**Comment by Dave-Morton** [comment]
This is an issue that was discovered with certain OS/server/browser combinations where the server variable `HTTP_REFERER` isn't being set. I'll be pushing a fix for this shortly. Instead of that particular error message you'l instead see a link to click that will take you to the proper page. Sorry for the inconvenience.

**Comment by Dave-Morton** [comment]
@AaronZhangL did you try the updated script, and did it help?

**Comment by Dave-Morton** [comment]
With no feedback in nearly 2 weeks, I think we can close this. If you have trouble with this still, we can reopen it then.
