### ISSUE TITLE
CSS manspeech

### ISSUE THREAD

**Issue by alianrkeasan** [Program-O/Program-O#328]
Hello, I would like to know if it is possible for the div class manspeech, the box that holds the answers of the bot, grow or expand down or bottom. It is always expanding upwards, but I've put an image above the container, and always that a big text comes from output it covers my image.

My CSS code is:
```
.manspeech {
  position: relative;
    display: block;
    min-height: 14px;
    min-width: 150px;
    max-width: 600px;
    max-height: 100px;
    width: auto;
    height: auto;
margin-top: 62px;

}


.botsay {

	
    color: blue;
    font-weight: normal;
    height: 100%;
    width: 100%;
    max-height: 200px;
	overflow-y: auto;
}
```
Thanks

**Comment by Dave-Morton** [comment]
Of course it's possible. That GUI page is only meant to serve as an example of what's possible. Feel free to alter it in any way you see fit. 😄 

One suggestion that I have for you is to add `overflow: auto` to the CSS for .botsay so that if it exceeds the max-height the conversation will still be accessible.

**Comment by alianrkeasan** [comment]
I think I've not expressed myself right.

I would like to know how to do it.

If you can help me.

**Comment by Dave-Morton** [comment]
Ah. I see. Let me see what I can come up with.

**Comment by Dave-Morton** [comment]
Ok, after playing around with both HTML and CSS layout of the page, I can only find one scenario where the speech bubble covers up an image, and that's if that image is placed within the `<div>` with the class of `manspeech`. If this is where your image is, then it needs to be moved, because it does not belong there. To be honest, it should also not be placed within any of that particular nest of divs. You should consider either placing the image in between `<div#convo_id>` and `<div.centerthis>`, or doing a complete redesign of the page's CSS and HTML to get everything to play well together. As I said, that GUI page is only an example, or a starting point, and isn't actually meant for production use. It was written several years ago, and web standards have evolved a LOT since then.
