### ISSUE TITLE
JSON Api Data Array

### ISSUE THREAD

**Issue by quiraang** [Program-O/Program-O#329]
Hi - closed issue #268 refers to including a data array in the JSON api response.
{"convo_id":"eadpiltbek9vt483jkmjb35sv3","usersay":"test","botsay":"This is just a test.","data":{"aiml_id":"468730","pattern":"TEST","thatpattern":"","topic":"","filename":"atomic.aiml","score":260,"track_score":"current bot, no topic to match, no thatpattern to match, direct pattern match, direct word match: test"}}

Part of that response array is "filename" - I've tried to use this but "filename"  is undefined. Am I missing something else that I need to do to activate the filename data item, or is this an error. Currently using version 2.6.7.

**Comment by quiraang** [comment]
Hi Dave,

thanks for the quick response.
Yes I'm using JSON in a modified version of the gui/jquery/index.php. I also have my own custom .js file as I'm using the chrome speech recognition features,.
if I do a          **console.log("json data: " + JSON.stringify(apidata));**
I get the following  with no filename in it -
json data: {"convo_id":"j1okp2pcca80buhb697dhldbf2","usersay":"hi","botsay":"Hi there. What is your name?","data":{"id":"160728","bot_id":"1","pattern":"HI","thatpattern":"WHAT CAN I CALL YOU","topic":"","score":259,"current_that":"hi there what is your name","aiml_id":"160728","track_score":"current bot, no topic to match, direct pattern match, direct word match: hi"}}

**Comment by Dave-Morton** [comment]
That's interesting that you seem to be getting only a limited data set. The current version in  the `DEV` branch provides a LOT more data, but looking at the output from my bot, I don't see a filename attribute there. Odd. Here's my current bot's JSON output:

```
{
    "convo_id":"Dave",
    "usersay":"hello",
    "botsay":"Hi there!",
    "data":{
        "convo_id":"Dave",
        "bot_name":"fooBot",
        "bot_id":1,
        "format":"json",
        "unknown_user":"Friend",
        "user_name":"Friend",
        "user_id":"9",
        "totallines":1,"conversation_lines":"1",
        "remember_up_to":"10",
        "debugemail":"dmorton@geekcavecreations.com",
        "debug_level":"4",
        "debugmode":1,"save_state":"session",
        "default_aiml_pattern":"RANDOM PICKUP LINE",
        "bot_parent_id":"1",
        "rawSay":"hello",
        "data":{
            "id":"91079",
            "bot_id":"1",
            "pattern":"HELLO",
            "thatpattern":"",
            "topic":"",
            "template":"Hi there!",
            "score":260,"current_that":"how are you",
            "aiml_id":"91079",
            "track_score":"current bot, no thatpattern to match, direct pattern match, direct word match: hello"
        }
    }
}
```
I'll look into this and see why filename isn't showing up.

**Comment by Dave-Morton** [comment]
Ok, I found the reason why filename wasn't included in the datastream. I've pushed a fix for it, but if you want to bypass downloading and installing a new version, you can simply alter one line in `chatbot/core/aiml/find_aiml.php`.

Look for the following line (around line 1042):
`SELECT `id`, `bot_id`, `pattern`, `thatpattern`, `topic`, `template` FROM `$dbn`.`aiml` WHERE`

and change it to this:
`SELECT `id`, `bot_id`, `pattern`, `thatpattern`, `topic`, `filename`, `template` FROM `$dbn`.`aiml` WHERE`

And that's it! Any future bot responses will include the filename, so that a sample output should look like this:

```
{
    "convo_id":"Dave",
    "usersay":"hello",
    "botsay":"How are you?",
    "data":{
        "convo_id":"Dave",
        "bot_name":"fooBot",
        "bot_id":1,"format":"json",
        "unknown_user":"Friend",
        "user_name":"Friend",
        "user_id":"9",
        "totallines":1,"conversation_lines":"1",
        "remember_up_to":"10",
        "debugemail":"dmorton@geekcavecreations.com",
        "debug_level":"4",
        "debugmode":1,"save_state":"session",
        "default_aiml_pattern":"RANDOM PICKUP LINE",
        "bot_parent_id":"1",
        "rawSay":"hello",
        "data":{
            "id":"93971",
            "bot_id":"1",
            "pattern":"HELLO",
            "thatpattern":"HI THERE",
            "topic":"",
            "filename":"update1.aiml",
            "template":"How are you?",
            "score":274,"current_that":"hi there",
            "aiml_id":"93971",
            "track_score":"current bot, direct thatpattern match, direct pattern match, direct word match: hello"
        }
    }
}
```
Let me know if you have trouble with this.

**Comment by quiraang** [comment]
Thanks Dave, that's great - I'll try it tomorrow and let you know if it works.
Cheers Simon

**Comment by Dave-Morton** [comment]
i'll most likely be renaming the JSON fields so that there isn't something like data.data.data (the current case), which could lead to some confusion. Most likely the new property names will be:

- data (top level, called by JS in the GUI)
- botData (gives bot details)
-aimlData (gives details of the selected and parsed AIML category, including the filename)

To my mind this makes more sense, and provides clearer object property names.

**Comment by quiraang** [comment]
Hi Dave,

I now get the filename, but I don't get the same data structure as shown in your example. Is there another code  version I should be using? I'm currently using 2.6.7
`{
  "convo_id": "j1okp2pcca80buhb697dhldbf2",
  "usersay": "Hi",
  "botsay": "Hi there. What is your name?",
  "data": {
    "id": "160728",
    "bot_id": "1",
    "pattern": "HI",
    "thatpattern": "WHAT CAN I CALL YOU",
    "topic": "",
    "filename": "that.aiml",
    "score": 259,
    "current_that": "hi there what is your name",
    "aiml_id": "160728",
    "track_score": "current bot, no topic to match, direct pattern match, direct word match: hi"
  }
}`

**Comment by Dave-Morton** [comment]
Most likely this is because you're a bit "behind" the  current state, or are using the latest from the `MASTER` branch. The most recent features will always be on the `DEV` branch, but while it's more advanced, it's also not necessarily as stable.  We also don't usually change version numbers unless we add something new, or substantially change core code to fix an issue (e.g. alter the database, or add a new feature), so while 2.6.7 is the current version, that's not always a true test of whether you're up to date. If you want to use the other data structure for your bot, I suggest downloading the latest from the `DEV` branch.

**Comment by quiraang** [comment]
Thanks Dave, you,ve been very helpful
