### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by MrAlicard** [Program-O/Program-O#338]
Hello,
When I try download the aiml files as aiml or sql file then I get this message: CSRF failure!
I wait to start the download automatically and after I get above message.
If I don't wait and click to click here then I don't get a zip file, instead I get a file without extension.

If I download the file and give a .zip extension manually then in the file there is the .aiml fájl or .sql fájl but those don't contain anything. They are empty.
I tried:
- master branch and dev branch, but the same result.
- Windows 10 with xampp , PHP 7.1.6 version
- Linux, php 7.0

All necessary requirements enabled in php: zip, mbString, curl, pdo

**Comment by Dave-Morton** [comment]
Are you seeing either admin.error.log, download.error.log or file.error.log in the logs folder? If so, can you please attach them here? I've tried this on both my Windows 10 development server and my Ubuntu VM with PHP 7 and don't see this problem at all.

**Comment by MrAlicard** [comment]
Hmm now I tried with php 5.6.13 version but same.
I don't see any admin.error.log, download.error.log or file.error.log. In logs folder has only index.php.
But the good thing is that if I don't wait till automatically start the download process instead I click to "click here" text then I get the zip file with aiml files and the content aren't empty.
I think then program-o isn't prepared 100% to use on php 7.0.

**Comment by Dave-Morton** [comment]
My testing of Program O includes doing so on both Windows and Linux (Ubuntu, mostly), with PHP versions 5.6.32 and 7.0.19, and so far, I'm not seeing this issue on any of my servers (and I have a LOT of servers to test it on). I'm still looking into it, however, so please bear with me. 😄

**Comment by MrAlicard** [comment]
Hmm then I don't know what is the problem. I only installed the xampp which has 7.1.6 php version. In xampp all extension was enabled default. I didn't need enable manually. Same with 5.6.13. When I installed program-o then in installation process was all "Pass" status.

**Comment by Dave-Morton** [comment]
Tell me please, are you trying, by chance, to access the downloads page without going through the admin? If you are, then this is actually expected behaviour. Most likely, the server environment variable HTTP_REFERER is not being set, which can happen when trying to access a given admin page without going through the admin itself (e.g. clicking on a link from inside the admin). If this is NOT the case, then your browser may not be sending the referer header for some reason, **or** the server environment variable HTTP_HOST may not be set correctly. ?in this case, going into the file library/misc_functions.php and commenting out the following line will help:

'if (false === $host || (false === $referer && 'localhost' !== $host)) die ('CSRF failure!');`

What that line does is look for the HTTP_HOST variable ($host) to make sure it's not set to Boolean FALSE, **or** the HTTP_HOST variable isn't set to 'localhost' AND the HTTP_REFERER variable isn't false. by commenting out that line, you're removing the test for those conditions and it should work fine. HOWEVER!! doing so puts your site at greater risk of malicious attacks, so should not be done except for testing. If you comment out that line and it works, let me know and I'll step you through the process of locating exactly which part of that condition test is failing. Since I can't duplicate the problem on my systems, we'll have to use yours to figure it out. :)

**Comment by MrAlicard** [comment]
Hmm I didn't commenting out the above code but I tried now with http://localhost/. I went to porgram-o with firefox and tried download the aiml file and it worked but if I use my public IP or 127.0.0.1 then I get CSRF failure! message.

**Comment by Dave-Morton** [comment]
That indicates to me that the code I mentioned is incomplete, and needs to be improved. I'll give it more thought and come up with a better implementation. In the meantime, if you want to comment out that check you should be ok for now. i'd only *really* worry about it in an enterprise level production site.

**Comment by Dave-Morton** [comment]
Closing this issue, as the OP hasn't responded in more than a month. @MrAlicard if you have more info to share, please reopen this issue. Thanks.
