### ISSUE TITLE
Problem with *

### ISSUE THREAD

**Issue by EnotYoyo** [Program-O/Program-O#341]
Hi!
I have a template: "* HOW ARE YOU" (in russian), but when I write: "Yo, how are you?", program-o does not find it. 

(sorry for my English)

**Comment by Dave-Morton** [comment]
Your English is just fine, really. :)
Try that same phrase without the comma and see if it answers as you would expect. It could be that Program O is splitting that input up into two separate inputs, and you may not have a category for just "how are you".

**Comment by EnotYoyo** [comment]
Without a comma does not work. And I have this category.

**Comment by AlekzNet** [comment]
@EnotYoyo could you please paste the AIML code here?

**Comment by EnotYoyo** [comment]
`    <category>
        <pattern>* КАК ДЕЛА</pattern>
        <template>
            <random>
                <li>отлично</li>
                <li>Cегодня хороший день</li>
                <li>Все ок.</li>
           </random>
       </template>
   </category>
`
This does not work for "Бро как дела?".

`    <category>
        <pattern>КАК ДЕЛА</pattern>
        <template>
            <random>
                <li>отлично</li>
                <li>Cегодня хороший день</li>
                <li>Все ок.</li>
           </random>
       </template>
   </category>
`
This work for "как дела?".

**Comment by Dave-Morton** [comment]
I'm afraid I'm not seeing this issue on my development install of Program O. Here's a running log of my bot's responses:

```
Friend: Бро как дела?
fooBot: отлично
Friend: Бро как дела?
fooBot: Все ок.
Friend: Бро как дела?
fooBot: отлично
Friend: Бро как дела?
fooBot: Все ок.
Friend: foo Бро как дела?
fooBot: Cегодня хороший день
```
My system specs:
- OS: windows 10 Pro 64 bit
- Server software/version: Apache 2.4.25
- PHP version 7.0.19
- MySQL version: 5.7.9

At this point I'll need to know the system specs for your install of Program O so that I can test it in one of my VM servers. Please provide to us the same system specs that I have listed and we can continue here.

**Comment by AlekzNet** [comment]
> This does not work for "Бро как дела?".

@EnotYoyo what do you get? Is it the default category? I wonder if there is another category that rewrites the input (via `<srai>`?) or there is a pattern beginning with Бро (`Бро *`?)

**Comment by Dave-Morton** [comment]
The only AIML categories I have in my test bot that are in Russian are the two that you've posted above. I'm not certain what you have. 😉 If you have your bot setup to allow for debugging, you can take advantage of the debug file viewer in the admin page to see what happens when you get a response that you don't expect. In order for the debugger to be effective, you should first make sure that the settings under the bot selection screen are in place. then chat with the bot to get the unwanted response, go to the debug file viewer and select the correct conversation ID, copy the contents of that file and paste it into your next post. I'll then look it over and see what's going on.

**Comment by EnotYoyo** [comment]
The error was in another file. But it was in English, I did not expect. Thanks.
