### ISSUE TITLE
Get date in hungarian

### ISSUE THREAD

**Issue by MrAlicard** [Program-O/Program-O#342]
Hello
Probably this is not bug only timezone problem but I write here.
I have this aiml:

```xml
<category>
   <pattern>IS TODAY SUNDAY</pattern>
  <template>Today is <date format="%A"/>.</template>
</category>
```

I get this answer: "Today is cs?t?rt?k." instead "Today is csütörtök." . This means "Today is thursday."

I tried change in php.ini the date.timezone to "Europe/Budapest" but didn't fix the problem. I looked with firefox, microsoft edge but same result. I use Windows 10 and hungarian language in OS. I tried also with http://byet.host/ and changed the timezone in cpanel to Europe/Budapest but same result.
I tried this with json api and json GUI but same result.

**Comment by AlekzNet** [comment]
>I get this answer: "Today is cs?t?rt?k." instead "Today is csütörtök." 

Do I understand correctly, that the problem is incorrectly shown umlauts? If yes, it's not about the time zone, but the locale settings in PHP (MySQL?), I guess.

**Comment by MrAlicard** [comment]
Hmm I don't understand why mysql, when php should do this job. I tried now so: `<date locale="hu_HU" format="%A"/>` but same result

**Comment by Dave-Morton** [comment]
I found a bug in the function that parses the `<data>` tag, but fixing that bug and using the locale `hu_HU` seems to have exposed another, more serious bug that I'm finding challenging to track down. I'll keep you posted on what I find.

**Comment by Dave-Morton** [comment]
After some research, I found that the Windows Hungarian language pack does NOT support UTF-8, and in fact is encoded in ISO-8859-2 instead. As a result, the Hungarian words for the days of the week in the `<date>` example given will not display correctly. this turns out to be a bug in Windows that has triggered other bugs in Program O. I'm correcting the bugs I'm finding, but can't do anything about the underlying cause.

By the way, of the five different locale codes that exist for Hungarian, only three of them actually work on Windows: "hu", "Hungarian" and "Hungatian_Hungary.1250". Sadly, they all cause problems with Program O when encoded in UTF-8. One thing that you might be able to do is to try using either ISO-8859-2, or Windows 1250 for the default character encoding for Program O. but that also means changing the encoding for the database as well, and that's not for the faint of heart.

**Comment by MrAlicard** [comment]
Hmm I see. I tried also with locale="en_US.utf8" and locale="en_US" but I don't get days in english. Instead I get hungarian with ? characters. I thought if I get the days in english then in aiml I can put in conditions and give to them after hungarian names. I gave in globalconfig file and php.ini America/New_York timezone but I get hungarian format days. I must have english OS or something else?

**Comment by Dave-Morton** [comment]
One thing to bear in mind is that you're still using a version that still has a bug in the code for the `<date>` tag that prevents the locale attribute from working properly. I'll be pushing the fix for that in a few hours that contains not only a fix for this, but also a bit of a code refactor to bring some of the admin scripts up to date. Part of the update will also include support for a couple of new attributes for the `<date>` tag (timestamp, which should be self explanatory, and offset, which will be described in detail in the CHANGELOG).

**Comment by Dave-Morton** [comment]
Well, it was more than a few hours, mainly due to the holiday, but I got the update I promised pushed. New version, but no need to do a clean install this time. :)

**Comment by MrAlicard** [comment]
Ok, Dave. Soon I will download the update soon and report to you what can I see from here. :)
