### ISSUE TITLE
Admin panel problems in DEV branch

### ISSUE THREAD

**Issue by MrAlicard** [Program-O/Program-O#345]
Hello,
When I updated to 2.6.8 DEV version and go to admin panel then I get direct this error top right side:
```
Program O has encountered an error. this may help:
    Error # 8
    Message: Undefined index: page
    File: C:\xampp\htdocs\chatbot\admin\index.php, line 111
```

Plus, I can't download aiml files from admin panel. The download process doesn't start.
I use XAMPP Version: 7.1.6 and Windows Version:  Home  64-bit and I use http://localhost/admin web address. If I use http://127.0.0.1/admin then direct I get `CSRF failure!` message.

When I go to admin panel index then I get admin.index.error.context.log and admin.index.error.log files.
In first log file has these things:
```
{removed in the interest of brevity}
```

In second file:
```
    Program O has encountered an error. this may help:
    Error # 8
    Message: Undefined index: page
    File: C:\xampp\htdocs\chatbot\admin\index.php, line 111
```

When I try download aiml files then I don't get error files.

**Comment by Dave-Morton** [comment]
That context file certainly adds a LOT of information that could prove useful for finding the cause of a problem, but it's also a potential security risk when posting it publicly, which is why I edited a portion of it to remove user credentials. Just a  heads up. 😄 

As for the initial error of the undefined index, I've found and corrected that particular bug. I'm still looking into why the downloads page isn't working as expected. I've found the cause (the `filenames` input variable is being sanitized as a string, not as an array), but haven't found a decent way to correct the issue "safely". I'm probably going to have to redesign the `clean_inputs()` function to account for the use of arrays, which probably means some sort of recursive filtering. I'll keep you posted.

**Comment by Dave-Morton** [comment]
I found the problem with the downloads page. It seems that refactoring the code in that page caused the variable `$filenames` to become `NULL`, rather than the array of filenames selected for download. that's been addressed. I also commented out the line of code in the `clean_inputs()` function that was mistakenly throwing CSRF errors under certain circumstances. I'll look into finding a better way to handle that.

**Comment by MrAlicard** [comment]
Now I don't get error when I go to admin/index.php but hmm. I can see if I try download english AIML files from program-o (which I uploaded from https://github.com/souri/Rey/tree/master/brain before) then I get these error (I get normally with .zip file, when I try download but I get plus these errors also)(BOT ID 1):

admin.download.error.log:
https://bitbin.it/6Qv2OY8R/

admin.download.error.context.log:
https://bitbin.it/AQvejyWL/

BUT if I try download hungarian aiml files which I wrote then I get these errors (plus I don't get with .zip extension file, I get without extension, when I try download)(BOT ID 2):
admin.download.error.log:
https://bitbin.it/LG0H4mMi/

admin.download.error.context.log:
https://pastebin.com/7u46eQCP

Those AIML-s which can you see in log files work perfectly when I test it.

**Comment by Dave-Morton** [comment]
The first problem is a bug, certainly, but it's one of not properly handling problems with invalid AIML (XML) that was created or edited within the admin. In your case, one of your AIML files (date.aiml) has an anchor tag (<a>) that was opened, but not closed. Looking at the context file, it's the 31st category in the file (index # of 30). this, BTW, is why I love that context file. It gives me ALL SORTS of useful information. 😉 

As for the second issue, that appears to be a similar problem, but with a different specific cause. More or less, the AIML file being parsed for download (szek.aiml) has a different type of glitch that was causing the `DOMDocument::loadXML()` function to complain. This time, however, it's saying that there is extra stuff after the XML document, which doesn't seem to really be there. I'm still looking into why that is, because the context file clearly doesn't show any such extra content. I'll copy the AIML from the context and try this on my system to see if I can reproduce the results.

**Comment by MrAlicard** [comment]
Yeah, this log reports are good. I can report better way all bugs or probably "bugs". 😃

**Comment by Dave-Morton** [comment]
By the way, in your file date.aiml, line 64 (pattern of IS IT SUNDAY) you'll find the following text, that needs to be removed:

`<html>        <a        </html>`

Getting rid of that should take care of the problem there (still working on the loadXML bug for that, though)

**Comment by MrAlicard** [comment]
The edit part fixed, thank you. :) I didn't touch the english aiml files. I only downloaded from mentioned github but thank you that you wrote this, so I don't do same mistake as have in english version. 😄 
Yeah, the download part for bot 2 doesn't work.

But now I get only admin.download.error.log not other. This is difference from before. 🌝 
And instead line 209, now has 210.
```
    Program O has encountered an error. this may help:
    Error # 2
    Message: DOMDocument::loadXML(): Couldn't find end of Start Tag bot line 32 in Entity, line: 32
    File: C:\xampp\htdocs\chatbot\admin\download.php, line 210

```

**Comment by Dave-Morton** [comment]
Try looking in the AIML file that it's complaining about, somewhere near line 32. You should find a `<bot>` tag with no trailing slash. If you can't find it, please drop the file here and I'll have a look.
