### ISSUE TITLE
thatstar tag index mis-counts/corrupts

### ISSUE THREAD

**Issue by robcain** [Program-O/Program-O#354]
**Title:** thatstar tag index mis-counts/corrupts
**Description:** thatstar index attribute seems to be corrupted/operating on wrong convoArr index perhaps
**Tested with:**  program-o version 2.6.8

**Test:** 
create test categories:

```xml
<category>
<pattern>TEST THATSTAR MULTIPLE</pattern>
<template>I say beans and franks for everybody</template>
</category>
```

```xml
<category>
<pattern>TEST THATSTAR MULTIPLE</pattern>
<that>I SAY * AND * FOR *</that>
<template>Yes, <thatstar index="1"/> and <thatstar index="2"/> for almost <thatstar index="3" />!</template>
</category>
```

**Expected Result:**

( reading: user input ->  bot output)::

TEST THATSTAR MULTIPLE
=>  I say beans and franks for everybody

TEST THATSTAR MULTIPLE
=> Yes, BEANS and FRANKS for almost EVERYBODY !

**Actual Result:**

( reading:  user input -> bot output)::

TEST THATSTAR MULTIPLE
->  I say beans and franks for everybody

TEST THATSTAR MULTIPLE
-> Yes, BEANS and EANS for almost FRANKS !

**Comment by robcain** [comment]
Update: 

I've analysed the debug log (thanks for feature that by the way devs) , inspected the relevant code, implemented & tested the following fix - it seems to work (at least for simple test case originally posted), hoe it helps others confronting this issue/bug - vis: 


program-o version: 2.6.8
file: /chatbox/core/aiml/parse_aiml.php
lines: 361 to 377

change from: 

...
    $tp = trim($aiml_thatpattern);
    $tp = str_replace("+", "\+", $tp);
    /*
        $tp = str_replace("*", "(.*)", $tp);
        $tp = str_replace("_", "(.*)", $tp);
    */
    $tp = str_replace(" * ", " (\S*) ", $tp);
    $tp = str_replace(" _ ", " (\S*) ", $tp);
    $tp = str_replace("* ", "(\S*) ", $tp);
    $tp = str_replace("_ ", "(\S*) ", $tp);
    $tp = str_replace(" *", " (.*)", $tp);
    $tp = str_replace(" _", " (.*)", $tp);
    $tp = str_replace("*", "(.*)", $tp);
    $tp = str_replace("_", "(.*)", $tp);
    $thatpattern_wildcards = str_replace("_", "(.*)?", str_replace("*", "(.*)?", $aiml_thatpattern));
...


change to: 

...
    $tp = trim($aiml_thatpattern);
    $tp = str_replace("+", "\+", $tp);
    $tp = str_replace(" * ", " (\S*) ", $tp);
    $tp = str_replace(" _ ", " (\S*) ", $tp);
    $tp = str_replace("* ", "(\S*) ", $tp);
    $tp = str_replace("_ ", "(\S*) ", $tp);
    $tp = str_replace(" *", " (.*)", $tp);
    $tp = str_replace(" _", " (.*)", $tp);
    $tp = str_replace("*", "(.*)", $tp);
    $tp = str_replace("_", "(.*)", $tp);
    $tp = str_replace("(\S(.*))", "(.*)", $tp);
    $tp = str_replace("(.(.*))", "(.*)", $tp);

    // Set pattern wildcards
    $thatpattern_wildcards = str_replace("_", "(.*)?", str_replace("*", "(.*)?", $aiml_thatpattern));
...

notes: this new pattern substitution sequence is copied directly from code the section of code immediately above this that deals with normal pattern-side wild card substitutions (with appropriate replacement of variable names) 

 - tested: against the original test pattern (see first post in this thread) - wild card substitutions, parsing and final output string now match expected result.

 
todo: further tests to verify correct behaviour – has anyone written a complete/proving test suite for  wildcards?

todo: i would really appreciate it if someone with more intimate knowledge of the code here could take a look at the above fix & confirm whether or not it is 'correct' or 'reasonable', or whether design of the original code here had some different intention?
 - many thanks

**Comment by patrickschur** [comment]
So sorry I didnt notice your issue until now. :(
Anyway, I can reconstruct the issue. So it's definitely there.
I'll take a closer look now. :)

Thanks

**Comment by Dave-Morton** [comment]
Hey, Rob.

I've taken a close look at the code you've posted and I think it looks great. I'm still testing things, but I think you're on the right track here.

One thing that this investigation has shown me is that in addition to the `that` wildcards having an issue, there is also a problem with parsing any `TOPIC` wildcards that may exist, in that there **IS** no parsing of them, since no code currently exists to do so. The AIML 1.0 standard surely allows for a `<topicstar>` tag, yet it's not accounted for, either in the code that creates them (the function we're currently working in), __OR__ in the code that parses that particular AIML tag. I'm currently working on addressing that. So thanks for the nudge that got me to see it. 😄 I'll have this fix pushed for testing shortly.

**Comment by Dave-Morton** [comment]
@patrickschur can you hop on Slack? We could discuss this.

**Comment by patrickschur** [comment]
@Dave-Morton I'm already waiting for you. :P

**Comment by robcain** [comment]
Very many thanks chaps. :) Look forward to the patch/next release.

( PS. I myself am just taking a look at the <gender> tag at the mo. (I know its in aiml 2 rather than aiml 1, but i've temporarily extended aiml.xsd in order to give it a go  - its a useful tag + i wanted to create my own aiml flavour eventuallly, & this seemed like a good pratice run.). needless to say, substution logic here  has a few issues too at present. ;) )

**Comment by Dave-Morton** [comment]
I'm afraid that when you do you're going to find some bugs. Worse yet, those bugs now exist on both the `DEV` __AND__ `MASTER` branches currently on GitHub. I'm working to correct them, but you may have to revert back to [this version](https://github.com/Program-O/Program-O/tree/94b0465c2e98f326b8693c6438689e3758745641) in order to regain functionality. Sadly, there was a SNAFU with my Git for Windows that caused the wrong branch to be pushed to. Once I realized that I had pushed to the `MASTER` branch by mistake, I (stupidly) pushed to the `DEV` branch, too. The bugs weren't found at that point, so things seemed fine. Then the bugs showed up. ☹️ If it takes me too long to get them found and fixed, I'll manually revert the `MASTER` branch to it's previously working version while continuing to repair `DEV`.

**Comment by Dave-Morton** [comment]
No news on this in more than a month, so closing this issue.
