### ISSUE TITLE
Admin CSS not responsive

### ISSUE THREAD

**Issue by spiffaz** [Program-O/Program-O#372]
I have tried to make changes to the style.css file in the Admin folder but the effects are not visible. 
I have successfully made changes to the gui pages but the admin isn't responding to change. Is there something I'm doing wrong?

**Comment by patrickschur** [comment]
Maybe your stylesheet is overwritten immediately. Try to define your stylesheet at the bottom of the script and/or set a `!important` rule for it.

**Comment by spiffaz** [comment]
I have discovered hat the problem is not that the CSS is unresponsive. It becomes responsive after a few hours. Is there nay way to fix this?

**Comment by Dave-Morton** [comment]
@spiffaz please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) so that we have enough information to at least make educated guesses about this issue. What we most need to see in this  instance is where your install of Program O is hosted (locally or on a remote server), but the rest is also important, so please gather the information requested about your Program O install and post it back here.

**Comment by Dave-Morton** [comment]
with no further input on this for over a month, it's time to close this. If you have more information to share, please reopen this issue so that we can help you further.
