### ISSUE TITLE
 Default Response

### ISSUE THREAD

**Issue by spiffaz** [Program-O/Program-O#374]
I have written AIML files for my bot. They have passed validation but when I upload them to the bot it repeatedly sends me my default response. What could be the issue and how can I fix this?

**Comment by Dave-Morton** [comment]
Have you tried setting up debugging for the bot and reading the debug file to see where it may be going wrong? Also, are there any error log entries that may relate to the problem? And lastly, before I can advise you more completely, it would help if you were to read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) so that you can provide some information that will help us to help you.

**Comment by OverlanAI** [comment]
Humm I have not run into that here but have run into the validation process can lie sometimes just to find out the file (BADANSWER.aiml or some other rare file) worked fine and passes on the next try, but thats for another day lol.
TNX

**Comment by Dave-Morton** [comment]
With more than 30 days of no response from the OP, I'm going to close this issue. If you have more information on this, please either reopen this issue, or open a new one.
