### ISSUE TITLE
Dev release 2.6.10 failing to match simple atomic categories

### ISSUE THREAD

**Issue by tringate** [Program-O/Program-O#383]
This is a tough one to recreate as you need a large AIML set so there are lots of categories to search for a match.

My assumption is that the failure is caused either buy single work categories or small character count categories.
Two simple categories I have failing are "sit" and "stand"

The problem is that the matches are for categories with words that have these character strings inside of other words.

"sit" is matching categories with words like "university" and  "sensitivity".
"stand" is matching categories with "understand".

The "search/edit AIML" tool does not show the matching category  if you use a space both in front and behind the single word.  If you do not place a space in front of the word it does show the categories that are being selected as well as the correct category.  The matching category ends with a word that has "stand" in it such as "understand".  It appears the program is now considering categories which do not contain the specific word but rather any word that contains that character string at the end of the word. 

These are all guesses since all of this AIML has been running for years with no issues.  It's not new AIML.

At first I thought my AIML set had become more AI than I thought it could be, only to discover it was finding matches that had nothing at all to do with what it was trying to find.

**Comment by tringate** [comment]
I did a dropped of the database and completely did a fresh restart.

I'm thinking this problem is caused by the "out of memory problem" or maybe the  
```
03/05/2018 03:10:57 - PHP ERROR [Warning] -Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in Unknown on Line 0
03/05/2018 03:10:57 - PHP ERROR [Warning] -Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/session) in Unknown on Line 0
`

Things work for awhile and then the AIML starts to fail in very strange ways.

Once it fails reloading the AIML does not fix anything.  I have to drop the database to get things working once again.

**Comment by OverlanAI** [comment]
well the session ID is one i do know and morton helped me solve by changing a few things.
There are two setings in php.ini that affect this: session.hash_function and session.hash_bits_per_character, and depending on the values of these settings, can cause a length restriction for the session ID of between 27 and 40 characters.

I run a large aiml set but in the bigger view  should be trivial for MySql and PHP since it can and does deal with DBs that are GB is size.
With that said and as your system grows you also have to alter my.ini php.ini and review apache php settings.
I run a simulator as the front end that talks to programO as a sub-system so i am use to running into what you are seeing as far as memory and performance issues goes.
Your post is covering a few problems but the convo_id can and has caused all sorts of problems once it has started to try and use a bad convo_id.
Anyway i would make the changes morton suggested first because all of the data in the DB uses it to ref. all of the other data.
As far as memory, to me that looks exactly like what i have seen in the past (not with programO) and is a matter of changing the max amount allowed in the servers ini's.
I have not run into the memory problem here but thats because I set my sever with heavy use in mind with huge data sets before I even bother starting a project on it.

TNX (my dimes worth)

**Comment by tringate** [comment]
After a database rebuild the memory errors have stopped occurring.  I understand the need to watch and adjust system parameters on the server, but I believe my issue was a problem that had been caused by a corrupt database.  I am unable to reproduce the problem since the database rebuild and a full fresh install of Program-O.

This problem can be closed as I believe the issue was not Program-O.
