### ISSUE TITLE
categories with no topic are left out when topic is set

### ISSUE THREAD

**Issue by Tasades** [Program-O/Program-O#386]
Hey, I think the GraphMaster logic is not correct.

If a topic is set for example TEST and I have following categories and the input is "WHAT IS TESTING", the wrong category is picked.

```
<topic name="TEST">
	<category>
		<pattern>*</pattern>
		<template>NOT THE RIGHT ANSWER</template>
	</category>
</topic>

<category>
	<pattern>* TESTING</pattern>
	<template>RIGHT ANSWER</template>
</category>
```

The NO TOPIC match should be prefered in this case because the graphmaster should make following decisions (I have left the THAT part out for this example):

- Is there a root node with a "_" --> no
- Is there a root with the word "WHAT" --> no
- Is there a root wiht a "*" --> yes
- Is there a next node with the word "IS" --> no
- Is there insteand a next node with the word "TESTING" --> yes
- Is there a next node with "TOPIC TEST" --> no
- Is there instead a next node with "TOPIC *" --> yes
- ANSWER FOUND --> return answer

But instead following path is choosen "*" - "TOPIC" - "TEST"

Am I thinking wrong? Or did I understand the intended AIML pattern matching logic?

Thank you for helping.

Tasades

**Comment by Dave-Morton** [comment]
Hi, @Tasades .

Ok, the first thing I should make you aware of is the fact that Program O doesn't use the Graphmaster algorithm to determine which category gets selected. The system used is rather different, and involves "scoring" potential matches based on more than just the values of the pattern, that and topic tags. Since bots in Program O can also be either a stand-alone, parent or child bot, this needs to be factored in as well, and Graphmaster isn't well suited for that additional complexity (at least, my experiments in integration haven't been very successful in that area). I'll create some testing AIML at some point between now and the weekend and see what I see with the most current version of Program O, and will get back to you when I have an idea of what's going on.

**Comment by Tasades** [comment]
Ok thank you very much for this information and the quick response.
If it using scoring then why is [ * with topic TEST ] preferred over  [ *  with one word match and topic * ]?
Thank you for your help. I am looking forward to your testing files.

**Comment by Dave-Morton** [comment]
It may also be helpful if you could provide a full debug file for a volley where you got the wrong response. You can obtain such a debug file by first enabling debugging and setting the debug level to "full", and the debug output to "file". This is done on a per-bot basis in the bot selection panel of the admin page. Once debugging options ae set, use the bot to get the desired (bad) response. The resulting debug file is located in the chatbot/debug folder, and has a file name that's the same as the conversation ID used. Those debug files are only good for one volley, and get overwritten each time the bot is used, so it's best to copy/move the file immediately after you get a result that you're looking for. Once you obtain the debug file, you can just drop it into GitHub here, and post as usual. the format of that file will take a bit of time/understanding to learn, but once you do, it's fairly straightforward. Each entry provides information on when and where the message was generated, down to the line number of where it was generated, as well as some (sometimes) useful information about what's going on.

**Comment by Tasades** [comment]
Here my debug files and test aiml
I have started the conversation and tried following inputs and got following response:

1. WHAT IS TESTING = RIGHT ANSWER
2. SETTESTTOPIC = <no response as defined>
3. WHAT IS TESTING = NOT THE RIGHT ANSWER

The debug files are numbered and labeled with the input I tried.
[DEBUG_FILES.zip](https://github.com/Program-O/Program-O/files/1815764/DEBUG_FILES.zip)

**Comment by Dave-Morton** [comment]
I downloaded the zip file and had a quick look at all of the debug files, and I noticed that in the last one (the one where you got the unintended answer) that the score for the correct response was lower than ti should have been. Sadly, I'm working on client tasks right now, so all I had time for was that quick look. I'll dig into it either this evening, or (more likely) tomorrow, when I have more time. It could be that the score bonus for being on topic needs to be reduced a little in order to allow the correct response to have a slightly higher priority. Meanwhile, here's what I'm looking at in that debug file. It may help to provide some insight into what's going on:

```
15-03-2018 15:32:08.15305[4][4] - Elapsed time: 1.000 milliseconds
[find_aiml.php][score_matches][548]
Sorted array $allrows:
Array
(
    [0] => Array
        (
            [id] => 2008
            [bot_id] => 2
            [pattern] => *
            [thatpattern] => 
            [topic] => TEST
            [filename] => Debug.aiml
            [template] => NOT THE RIGHT ANSWER
            [score] => 302
            [current_that] => 
            [aiml_id] => 2008
            [track_score] => current bot, direct topic match, no thatpattern to match, pattern star match
        )

    [1] => Array
        (
            [id] => 2009
            [bot_id] => 2
            [pattern] => * TESTING
            [thatpattern] => 
            [topic] => 
            [filename] => Debug.aiml
            [template] => RIGHT ANSWER
            [score] => 254
            [current_that] => 
            [aiml_id] => 2009
            [track_score] => current bot, no topic to match, no thatpattern to match, star word match, direct word match: testing
        )

)
 
-----------------------
```

**Comment by Tasades** [comment]
Thank you for explaining the debug files. I will test a few more cases.

**Comment by Dave-Morton** [comment]
This issue has made me realize that something was missing with regard to tracking the scores for each potential category. It's not enough to know the "why" of the score (current bot, matching topic, etc.); it's also good to know _how much_ each of the "whys" contribute to the overall score. The difference between the scores of those two categories (302 for the wrong response vs 254 for the right one, or 48 points) is all well and good, but it's also important to know where that point difference came from so that it will be possible to figure out which score values need to be changed in order to make it behave as intended. I've got some other bug fixes in the works as well, so won't be releasing this new code right away (I need to test the other bug fixes first), but I'm hoping to get the time to get this all out by mid-week next. I'll keep you posted.

**Comment by Dave-Morton** [comment]
@Tasades I've had a long conversation with @tringate over this issue, and it turns out that the behaviour you're seeing is actually the way AIML was intended to work. Whenever you're in a given topic (by earlier setting the topic with a `<set>` tag), then this is the topic you're in, and only AIML categories within that topic are selected. The only way to exit a topic is to have an AIML category that is purpose-built to do so. the best way to accomplish this is to use a single `star` wildcard (__NOT__ the `underscore`) for a category pattern like this:

```
<category>
    <pattern>*</pattern>
    <template>
        <think><set name="topic"></set></think>
        {whatever you want here foe the actual response}
    </template>
</category>
```

As such, the behaviour you're seeing isn't really a bug. I wish I could give you better news than that, but there you are.

**Comment by tringate** [comment]
The TOPIC tag that sets the scope of the AIML  considered to be "inside" the TOPIC followed these rules for release 1.0 of the AIML.  I do not have access to the pattern match documentation for release 1.0.1 but I don't think that it was changed.

In your test case you have used a catch all category which is going to prevent any categories outside of the TOPIC from being search.  Once a match is found, it does not continue to look for other matches of lessor precedence .  In your assumption you are assuming each level is tested both inside and outside of the TOPIC but that is not how TOPIC works in V1.0 of the AIML.

In your case the search for a match stopped at the "DEFAULT with a TOPIC" step of the search.

That is why I recommend that in a topic you provide an ATOMIC way to exit the TOPIC and use the catch-all inside of a TOPIC very carefully, or not at all.
I typically place this type of catch-all in my topics while developing them.

`<category><pattern>*</pattern><template>`
`<think>`
`<set name="topic"></set>`
`</think>`
`<srai><star/></srai>`
`</template></category>`


 How are the patterns matched?
When a client enters an input, the program scans the categories to find the best match. By comparing the input with the patterns in the following order, the algorithm ensures that the most specific pattern matches first. "Specific" in this case has a formal definition, but basically it means that the program finds the "longest" pattern matching an input.

Search order:

ATOMIC with a THAT
ATOMIC
DEFAULT with a THAT
DEFAULT

Example:.

What type of heaters do you have?

will match the ATOMIC: "WHAT TYPE OF HEATERS DO YOU HAVE"
and not the REDUCTION of: WHAT TYPE OF *

The ATOMIC category will always take precidence over any other type of category, other than another ATOMIC with a THAT.
If you have two identical patters, but one has a THAT, then the THAT category, will take precidence over the ATOMIC category, if the THAT matches the bot's previous response.

If neither of the above is true, then a REDUCTION that matches part of the pattern will give it's response, and finally if none of the above matches, then the catch-all or pickup will take over.

Any categories that are contained within a TOPIC section will be searched first if the current setting of TOPIC matches a TOPIC section. This results in an extension of the search order to the following:

ATOMIC with a TOPIC and a THAT
ATOMIC with a TOPIC
DEFAULT with a TOPIC and a THAT
DEFAULT with a TOPIC
ATOMIC with a THAT
ATOMIC
DEFAULT with a THAT
DEFAULT

The TOPIC sections are always searched first if they match the current setting of TOPIC. This permits the botmaster to have identical category patterns within a TOPIC section and in the GENERAL section.

The wild-card character "*" comes before "A" in alphabetical order. For example, the "WHAT *" pattern is more general than "WHAT IS *". The default pattern "*" is first in alphabetical order and the most general pattern. For convenience AIML also provides a variation on "*" denoted "_", which comes after "Z" in alphabetical order.

**Comment by tringate** [comment]
I failed to mention that if you used the catch all like you put in your test case, and then did the type of  `<srai>` to `<star/>` like I did you would create an endless loop within the TOPIC.  It is imperative you turn off, or, disable the TOPIC before you continue to look for a match.

**Comment by OverlanAI** [comment]
Yah found that out after testing it, It also did not want to let go of the topic after the test when it should have.
Might be the same thing as the loop.
tnx

**Comment by Dave-Morton** [comment]
This issue has achieved "stale" status (no  new info in over a month), so will be closed. If new information becomes available, please either reopen this issue, or create a new one. Thanks.
