### ISSUE TITLE
javascript inside AIML

### ISSUE THREAD

**Issue by sayedfalil** [Program-O/Program-O#396]
> <category>

    <pattern>*</pattern>
    <template><a href="http://abc.com?q=<star/>">Google Search for <star/></a></template>
</category>  

> 

I am checking for an option like, whatever user type it will append to the end of the URL. Is there any way to do this, The above code is not working for me.

**Comment by Dave-Morton** [comment]
That code won't work for you because you're trying to have a "tag within a tag". With AIML 1.0 this is not possible to do, but there is a (rather complicated) way to get around it with Program O. Take a look at the file chatbot/addons/custom_tags/custom_tags.php and look for the function `parse_google_tag()`. That function does exactly what you want to do, with google.com as the "root" site. You can get same functionality for your own URL by first duplicating that function, assigning a new "tag name" to the function in place of "google" (make sure the function still has both "parse_" and "_tag" intact - those are vital to the new function working properly), then using a new, custom AIML tag for your bot. The function will automatically be called when your new AIML tag is encountered, and will create the proper link for you that the user can then click on.

**Comment by Dave-Morton** [comment]
It's been a month without further information or feedback from the OP, so this issue is closed. If you have more information to share, please either reopen this issue, or create another. Thanks.
