### ISSUE TITLE
how can I get value from star

### ISSUE THREAD

**Issue by ngocquynh85** [Program-O/Program-O#400]
hi, how can I get value from star.
Ex:
`<get name= <star /> />`

**Comment by Dave-Morton** [comment]
Well, you can't get it _that_ way, that's for sure. 😛 
What you're trying to do there is placing one4 tag (in your case, the `<star>` tag) within the attribute of another one (the `<get>` tag), and this is forbidden in XML, of which AIML is a subset.
In order to obtain the value you're looking for, you have to use a little "trickery", but fortunately, Program O already has support for such trickery. 😄  All you need to do is use the "*" token, instead. For example, to get the first `<star>` in the category ( the one with either no index, or an index of "1"), you use the following syntax:
`<get name="*"/> - __OR__ - `<get name="*1"/>` (although, looking at the code, "*1" may not actually work. I'll have to put fixing that on my ToDo list)
If you need to access a _different_ star (e.g. with a different index value), the format is pretty straightforward, as well:
`<get name=*2"/>`, `<get name=*3"/>`, etc.
Just bear in mind that if no such star exists, you'll get back the literal string value, "undefined".
