### ISSUE TITLE
condition with value=""

### ISSUE THREAD

**Issue by ngocquynh85** [Program-O/Program-O#401]
example: 
I set var: 
`<set name="email"></set>`

then, check condition

```xml

<condition name="email">
<li value="undefined">
 value email: undefined
</li>
<li value="">
value email empty
</li>
<li> dont know</li>
<li value="*">All</li> 
</condition>


```

I expect it will show "value email empty" but it show All.

And, I don't know what case will use `<li></li> `

**Comment by Dave-Morton** [comment]
Well, first off, you should know that with condition tags, order is VERY important, because it will stop at the very first tag in which the condition is met. This may or may not apply to your specific circumstance, but it's something to think about. I bring it up because the bare `<li>` tag should be the last element within the condition, and it is not in the example you're showing.

There are also a number of bugs currently in the functions that parse the `<condition>` tags, and it's likely that those bugs may be what's causing the issue you are seeing.

Lastly, you will never see a match for `<li value="">` because the "default" value for a client property (or predicate, as they're called by Pandorabots) is not an empty string, but "undefined". As such, I would recommend writing the AIML like so:

```
<condition name="email">
    <li value="undefined">value email: undefined</li>
    <li value="*">All (this would actually match the value of the first <star> tag, if present)</li>
    <li> don't know</li>
</condition>
```
There was a debate several years ago regarding how to handle client properties that had not been set yet, and the general consensus at the time was to set it to "undefined", so that's how it's been ever since. the main reason was that it's far easier to deal with a client property that has _some_ value (e.g. "undefined") than it was to figure out whether a returned blank value was intended, or the result of a bug in the bot's AIML. At the time, the Program O forums (now defunct) had a large number of posts about "empty" values being returned, the vast majority of which were the result of poor AIML code. It was a right pain in the neck to deal with. 😄

**Comment by ngocquynh85** [comment]
yes, thank you so much for quick reply.
BTW, what kind of wildcard can use ?
`# _ ^ *`
