### ISSUE TITLE
can I use multi name with condition tag ?

### ISSUE THREAD

**Issue by ngocquynh85** [Program-O/Program-O#404]
Hi admin,
Could I use multi name with condition tag ? for example
```xml
<condition>
  <li name='var_fullname' value='undefined'><srai>UPDATE FULLNAME</srai></li>
  <li name='var_tel' value='undefined'><srai>UPDATE TEL</srai></li>
  <li name='var_address' value='undefined'><srai>UPDATE Address</srai></li>
</condition>
```

**Comment by AlekzNet** [comment]
What happens if you try it? ;)

**Comment by Dave-Morton** [comment]
The short answer is yes, but that's not the way to go about it. In order to do what you're wanting to do, your AIML code should look like this:

```
<condition name='var_fullname' value='undefined'><srai>UPDATE FULLNAME</srai></condition>
<condition name='var_tel' value='undefined'><srai>UPDATE TEL</srai></condition>
<condition name='var_address' value='undefined'><srai>UPDATE Address</srai></condition>
```
Program O is designed to work with `<condition>` tags such that it will return only the _first_ match it comes across and stop trying to find more matches, so the way you wrote your code, it would only update ONE of those items, ignoring any other potential updates that might be required. By writing the AIML the way I did, you get any and all updates that might be needed all at once, with no extraneous text responses for those that don't get matched.

Hope this helps. 😄

**Comment by AlekzNet** [comment]
Thanks much Dave! Very elegant!

You learn something every day...

**Comment by Dave-Morton** [comment]
Happy to help. Please let me know if you have trouble with this. 😄
