### ISSUE TITLE
Initial Default Response

### ISSUE THREAD

**Issue by sayedfalil** [Program-O/Program-O#405]
Hi there,

I have faced an issue with AIML conversation, I am using multiple AIML  files in chatbot but whenever  I start the conversation with the chatbot it is showing “No AIML category found. This is a Default Response" initially and if I continue the same question again it gives a proper response.
ex: 
User: Hi
bot: No AIML category found. This is a Default Response.
User: Hi
bot: Hello

**Comment by Dave-Morton** [comment]
@sayedfalil In order to be able to help you, we need some information. Please look at this [wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to see what sort of information we need. Also, if you see any error logs in the logs folder, posting them would help, as well as any debug files that may be generated from the "No AIML" response. Debug files are overwritten with each new volley, so please be sure to copy/move the debug file before chatting with the bot again. Once we get the information we need, we can do much better than making wild guesses. 😄

**Comment by sayedfalil** [comment]
Hi there,

I’ve checked the conversation log  of program-o and  attached the image 

![screenshot 166](https://user-images.githubusercontent.com/17051379/39326878-f486f0d4-49b3-11e8-9fcd-14d1634875d5.png)




But here it will respond properly when sending the same message again.

I can't see this in my unknown inputs log in program-o,

And then i got these from my debug log 


> 25-04-2018

 06:47:07.23003[2][4] - Elapsed time: 0.021 milliseconds

[conversation_start.php][Called outside of function][199]

Details:

User say: HI

Convo id: 6jl921omnml75fc1snelurnht5

Bot id: 2

Format: json 

> 

I am facing these issue in my all program-o bots 
Thanks

**Comment by Dave-Morton** [comment]
Ok, let's try this another way. Please provide the following information, so that we can test on a server that's closest to yours:
1. What _specific_ version of Program O are you using, and from which development branch (MASTER or DEV)?
2. Is your Program O install on a LOCAL or REMOTE server?
3. What is your server's OS and version?
4. Which version of PHP is your server running
5. What server software (Apache, nginx, IIS, etc.) and version does your server run?

These may seem like silly questions, but they sometimes make a HUGE difference, so knowing these things helps us to use or create a virtual machine that matches your specific setup in order to run tests that will actually show useful results.

For example, for my Program O install on my primary development server (the one I write the code for Program O on), I would answer the questions above like this:

1. Program O version 2.6.11, DEV branch (not pushed yet)
2. Local server
3. Windows 10 Pro, ver. 1709, build 16299.371
4. PHP version 7.0.19
5. Apache 2.4.25 x64 thread safe

**Comment by sayedfalil** [comment]
Hi There,

These are the configuration of my server which I running program_O.

1) What specific version of Program O are you using, and from which development branch (MASTER or DEV)?
    
     ⇒  Program O
                             Current Local Version: 2.6.8
                             Current GitHub Version: 2.6.8
                             Current Branch: Master
2) Is your Program O install on a LOCAL or REMOTE server?
     ⇒ Remote server.

3) What is your server's OS and version?
    ⇒ Ubuntu 16.04.4 LTS 

4) Which version of PHP is your server running
   ⇒PHP 5.6.34-1+ubuntu16.04.1 

5) What server software (Apache, Nginx, IIS, etc.) and version does your server run?

  ⇒Apache/2.4.18 (Ubuntu)
6) Using MySQL database 
    ⇒ 5.7.21-0 ubuntu0.16.04.1

Thanks

**Comment by Dave-Morton** [comment]
Thanks for that information, @sayedfalil. My first suggestion is going to be that you update your Program O install to version 2.6.10 from the `DEV` branch, which has a large number of improvements and bug fixes compared to the latest from the `MASTER` branch (I'll be meeting with the rest of the dev team to see about updating the `MASTER` branch, but not till after this weekend). In the meantime, I have a VM that closely matches your setup, so I'll do some testing to see what I can find.
