### ISSUE TITLE
Underscore not treated the same as star in patterns

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#424]
When a STAR is used alone as part of THAT response, and assuming other single STAR are also in the normal pattern, I get very odd results.
Many times we may have set a that pattern as just a STAR to trigger the topic no matter what the user said.
Why underscore works and Star works , they are not treated the same at all.
Underscore Overrides STAR depending on mode "which_response=" (top down or bottom up or random.
I did a bit of Libra logic It seems there should be no difference between the two wild cards we have.
In fact as far as i know at this point in AIML it should not matter.
Anyway making it all STAR is not the same ask making it all Underscore when used in a THAT input.
I have changed any pattern input to a THAT pattern as underscore not star.
TNX  <-- Just misunderstood most days :)

**Comment by Dave-Morton** [comment]
Actually, the underscore has the highest priority with regard to matching, and this is by design. Underscore wildcards are chosen over __everything__, even `direct word matches`, when they fir the input. Underscores are very powerful, but can also be either overused or misused, so should be used very sparingly, and under only very specific situations. For example, one would use an underscore wildcard for "word replacement". the following example shows how it would work:

```
<category>
    <pattern>_ strange</pattern>
    <template>
        <srai><star/> odd</srai>
    </template>
</category>
<category>
    <pattern>_ strange *</pattern>
    <template>
        <srai><star/> odd <star index="2"/></srai>
    </template>
</category>
<category>
    <pattern>strange _</pattern>
    <template>
        <srai>odd <star/></srai>
    </template>
</category>
```
The above AIML categories effectively replace the word `strange` with the word `odd`. the underscore is used to make sure that __ANY__ instance of the word `strange` is replaced with the word `odd`, and then reprocessed. this is just about the only _real_ use for the underscore that won't cause unexpected results. NEVER, under ANY circumstance, should the underscore wildcard be used by itself, as it will literally match __*EVERYTHING*__, including itself, over and over again, causing an infinite loop, and breaking the script.

**Comment by OverlanAI** [comment]
Okay so the use of a single underscore as the PATTERN for a THAT PATTERN statement will not work intentionally then. Vrs  single STAR as the PATTERN for a THAT PATTERN statement will work.
There is other documentation that i read that suggested that the old _ did the same thing as an * for backward compatibility of newer AIML, This is what lead me to posting this given the contradiction.
Anyway I no longer use underscore to avoid making new problems that can be avoided in ether case.
tnx

**Comment by OverlanAI** [comment]
A suggestion might be to alter the PHP script so that it make no difference between _ and * and simply treats them the same so no re-editing is needed.
 Seems better to avoid a worse problem of  "causing an infinite loop".
TNX

**Comment by OverlanAI** [comment]
For this problem i just hacked it so when i runs into an underscore in the pattern or worse in a that pattern to swap it our for a star. How correct that is in the AIML world idc lol.
It just seems silly to me having it processing underscores at all vrs make it mean exactly the same thing as a star. So i just have it swap it out so that older AIML will still work without editing.
TNX
