### ISSUE TITLE
Some members can't talk with the bot

### ISSUE THREAD

**Issue by StrangerGithuber** [Program-O/Program-O#455]
Hello
After awhile some people can't talk with the bot. I don't know why. For example I can talk with the bot but some people can't instead they get the default error message which i gave in the admin panel.
I don't get in logs folder any log file. I have only the debug.
Here is the debug (for example one of the member): https://pastebin.com/P1V6jYjG

I found this:
```
PDO_functions.php][db_fetchAll][202]
An error was generated while extracting multiple rows of data from the database in file /home/mralicar/public_html/robotok/chatbot/core/aiml/find_aiml.php at line 1053, in the function find_aiml_matches.
SQL: SELECT `id`, `bot_id`, `pattern`, `thatpattern`, `topic`, `filename`, `template` FROM `botdatabase`.`aiml` WHERE
    bot_id = 1 AND (
        'HELLO' LIKE (REPLACE(REPLACE(`pattern`, '*', '%'), '_', '%'))
        OR 'I CAN T ANSWER TO YOU BECAUSE THERE IS AN ERROR REPORT THIS TO MY MASTER' LIKE (REPLACE(REPLACE(`thatpattern`, '*', '%'), '_', '%'))
        OR ''SOMEWHERE I BELONG' BY LINKIN PARK' LIKE (REPLACE(REPLACE(`topic`, '*', '%'), '_', '%'))
        OR `pattern` LIKE 'RANDOM PICKUP LINE'
    )
    # ORDER BY `id` ASC, `topic` DESC, `pattern` ASC, `thatpattern` ASC;
Params: Array
(
    [:bot_id] => 1
)

PDO error: Array
(
    [0] => 00000
    [1] => 
    [2] => 
)

PDO_statement error: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOMEWHERE I BELONG' BY LINKIN PARK' LIKE (REPLACE(REPLACE(`topic`, '*', '%'), '_' at line 5
)
```

But probably there are more.
But it is strange. First 2 weeks everybody could talk with the bot but nowadays some people can't talk with the bot because of the same problem.
When they get one time the error message then they can't talk anymore with the bot until I don't clean up the **client_properties** table.

**Comment by OverlanAI** [comment]
Well that looks like it may be a few things but for now you can type in your chat
clear properties
Thats an internal command to clear the bot from chat.
What could be going on is garbage char are getting in from a user that it should be filtering out OR some really long input string from a user trying to type in a book lol.
I will check that section of the php and see.

What type of interface do you use to talk to your bot with?
Are you using the example web pages that come with programO?
If not are you using your own script via the JSON pipe and programO is just a back-end to your script?

Anyway "clear properties" will clean out the junk if its acting odd in the mean time.
I will take a peek at the php when i get a chance.
For my middle-ware JSON interface i added a counter that after so-many 100k rounds of chat it automatically sends it a "clear properties" command weather it needs it or not but thats not a fix lol.
TNX

**Comment by StrangerGithuber** [comment]
Hmm I will try it when someone has again this issue. Hmm but it is strange anyway that some people get one time the default error message and after they can't talk with the bot. Hmm is it possible that if a person send many messages and the bot don't answer super fast, only after 30 seconds then the bot tries to answer to all messages which collected? I mean that my hosting is not super fast so it takes some time for the bot to answer to everything.

**Comment by OverlanAI** [comment]
@StrangerGithuber 
I think one of 2 things may be going on, where it is trying to process invalid char. that may be ether from the users input OR somehow in your AIML files from a bad edit.
I have not looked into the section of php that is getting angry yet.
In my external script i have it remove any HTML codes from the users input (if there is any) then do a trim before it sends what the user said to program-o.
That i do, just to be sure someone or thing is not messing with it but it should not be needed since internally Program-O also filters out such things.
It is also possible during edit of your AIML to put back in char's that mysql does not like or by word censor. Verify your aiml files using the program-o validate script to make sure none of your AIML has gotten messed up somehow.
Anyway thats all just guessing on my part but i have caused it to freak out before if any or all of that happens.
Your exact problem i cant say that i have seen before so thats why im asking a lot of questions first.
TNX

**Comment by OverlanAI** [comment]
`[2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOMEWHERE I BELONG' BY LINKIN PARK' LIKE (REPLACE(REPLACE(`topic`, '*', '%'), '_' at line 5`

That really bugs me because it is cut off and wold be a bad Mysql command because it is not all there.
Like something else interrupted it during the process.
Idk .. something timing out because it is taking too long to process (guessing) but that looks all messed up whatever happened there and that is TOPIC on top of that.
Ill keep poking around but thats a very strange error.

**Comment by StrangerGithuber** [comment]
Well I am using Discord to chitchat and it filter such things + I convert the special character messages to point **.** so program-o can handle easier. Of course before I send to program-o the messages.
Well indeed it is strange.

**Comment by OverlanAI** [comment]
As to why it happens to some users and not others (random) is because each user it tracked separately in the database.
If user 2 has built up a lot of garbage then it would just bother that one user and not the others.
When you use the command in chat, it clears ALL of it out for ALL users so you do not want it to be abused.
It forces a type of GC so i would suggest that only you as admin do that when you get reports about the problem.
That also is not a FIX, it is just a fast way clear it up when you need to.
For me i hacked in a counter that triggers that to happen on its own as a type of general maintenance.
But that will not stop the problem it just lets you recover from it.
TNX

**Comment by StrangerGithuber** [comment]
Indeed. Plus I saw that when I cleared client_properties table then the bot didn't remember the user's name. The user needed to say again his/her name again to the bot to remember the name.

**Comment by OverlanAI** [comment]
Well i cant see anything in the php that would give that type of error.
You need to narrow it down to something that causes it to happen in order to trace it out.
The logs are reporting just the effect and not what condition that causes it.
Im just a tester and hacker not a dev so they may be of more help in this case unless you can narrow it down to what is triggering it.
Anyway i gave it try anyway and wish i could have been more help.
If i do discover anything i will let you know but right now i have no way to make it happen on my systems.
TNX

**Comment by StrangerGithuber** [comment]
Well when it will happen again then I will share the client_properties table and it will be easier to see the problem probably and I will give the convo_id too that which ID bugged. 👍

**Comment by OverlanAI** [comment]
As best as i can find is the lack of sync to the each round. Also i know of a problem when it comes to convo-id and user-id that will make it barf.
For real humans i use use UUID as convo id and for non humans i use the object name as uuid.
But there is is a problem with both that has to do with php and mysql bobby brown problems.
I have to also set a form to the convo-id and the userid as in we dont try to pass to program anything that can be a risk.
So i would start to take a closer look at both and you may find it is saving you from Bobby brown.
I do not know that it is your problem but i do know as a hacker you need to check and test what is in each.
It took hippo exactly 3 min 22 sec to wipe the grin off my face but thats why hes crew.
I still cant say i know the cause of your problem but you may want to check the your convo_id and user-id too, Things get pissed lol.
Mean time i still cant make it do the error you have and hippo gave up and went back to his swamp.
I have nothing i can blame as far as core goes right now.
TNX

**Comment by StrangerGithuber** [comment]
Well for convoid I use the discord user id and put there the discord word as you can see on pastebin. For example: discord461980265573777438 .
To "filter" all special characters in the text, I use this regex method:
`string.replace(/[^\w\s]/gi, '.');`

So it will change in theory all special characters to **.**

**Comment by Dave-Morton** [comment]
Hello, @StrangerGithuber! I'm sorry that nobody has responded to your issue yet. I'm currently on a sabbatical, trying to get my pancreatic cancer under control (NOT fun), but I'm feeling well enough to pop in and see how things are going. I haven't yet read all of the posts, but I will, right after I post this so that I can best understand your needs, and how I can help.

**Comment by Program-O** [comment]
The problem seems to be that your input has single quote marks in it...
```OR ''SOMEWHERE I BELONG' BY LINKIN PARK' LIKE (REPLACE(REPLACE(`topic`, '*', '%'), '_', '%'))```
I am looking into why there were not striped out

**Comment by Program-O** [comment]
Hi,
I cannot replicate this,
These are the steps i did...

Input 1 >lets talk about 'le freak' by chic
Input 2 >what is the topic

```SELECT `id`, `bot_id`, `pattern`, `thatpattern`, `topic`, `filename`, `template` FROM `programolocal`.`aiml` WHERE
    bot_id = 1 AND (
        'WHAT IS THE TOPIC' LIKE (REPLACE(REPLACE(`pattern`, '*', '%'), '_', '%'))
        OR 'WHAT DO YOU REALLY WANT TO ASK ME' LIKE (REPLACE(REPLACE(`thatpattern`, '*', '%'), '_', '%'))
        OR 'LETS TALK ABOUT LE FREAK BY CHIC' LIKE (REPLACE(REPLACE(`topic`, '*', '%'), '_', '%'))
        OR `pattern` LIKE 'RANDOM PICKUP LINE'
    )
    # ORDER BY `id` ASC, `topic` DESC, `pattern` ASC, `thatpattern` ASC; ```


As you can see from my sql there are no quotes around 'LE FREAK" even though my input had them.

Can you please provide the exact conversation steps to repeat this and do an sql dump give the aiml of any aiml patterns the conversation uses.
Thanks!

**Comment by StrangerGithuber** [comment]
I need to wait to happen again. When it will happen again then I will share the client_properties table and which convo_id has problem and then it will be easier for you all too see what is the problem. But I can't do anything now, only wait to occur again.
But what I can say is that the person didn't talk about linkin park. The linkin park and SOMEWHERE I BELONG are in bot properties. I put the value in the admin panel->Bot Personality->favoritesong.
Value:
**'Somewhere I Belong' by Linkin Park**

@Dave-Morton Good to see that you feel better. 👍 I understand what hell do you have. Not long time ago I came out from hospital and currently I am in recovery state but it is hard too. You need to be strong and everything will be fine. 🥇

**Comment by Program-O** [comment]
I think if you remove those single quote marks from your bot property it wont happen again

**Comment by Dave-Morton** [comment]
Given that the `<bot>` tag can, in certain circumstances, be used as part of an input pattern (e.g. can be found within the `<pattern>` tag), having characters other than letters, numbers or spaces isn't actually allowed. Just thought I'd throw that out there. 😄

**Comment by StrangerGithuber** [comment]
Hmm if it the case then I will close this issue for now. I didn't get the error again since I opened the issue because the person who got mostly the problem is not online often so I can't give an example to client_properties. If it will occurs again then I will reopen this issue. Thank you the response everybody. :)
