### ISSUE TITLE
How to upgrade existing Program-O v2.x

### ISSUE THREAD

**Issue by Delilovic** [Program-O/Program-O#462]
Hello!

I can not see an explanation how to upgrade Program-O if you already have a version greater or equal to 2.0

First time we use the installation script and now should we only extract the zip file and paste it over the current Program-O folder, will this break something? 

Kind Regards

**Comment by Program-O** [comment]
You should use git to handle your updates.
Go into the root of your folder and in the terminal type "git pull"
Or if you use the Git GUI then perform a pull from inside that.
If you have made any changes to your local files since the previous update 
then you will need to resolve and commit any conflicts to your local branch before you can complete the pull.
There are loads of information about it here
https://try.github.io/
And if you need specific help with git then the quickest place to get a response will be here
https://stackoverflow.com/search?q=git+pull
Good Luck

**Comment by Delilovic** [comment]
Thank you for the reply.

I already know how to use Git, but I am not sure if we mean the same thing. Do you say that to upgrade the Program-O app I need to use Git? Isn't Git only used if you change the code your self and contribute to the project, not for the usage of the app it self. 

More details:
[I want to fix the version error as shown in this image.](https://ibb.co/cSvj9U)

**Comment by Program-O** [comment]
If you want to get all the changes from the project contributed by others and the team itself you use git to pull all the code changes down since your last pull.
:)
If you are unsure just make sure you back everything up first.
I am not sure what has changed since version2.0 so make sure you read through and see if you have to run any db updates but if you want the latest code just do a pull.
Good luck!

**Comment by Dave-Morton** [comment]
There have been several changes to not only the database, but the codebase itself since version 2.0, so it's a REALLY good idea to do a clean install to a fresh directory, then create your bot(s) over again, if you're actually upgrading from 2.0. If you can tell me the current version of Program O that you're using, I can give you more specific suggestions.

**Comment by Delilovic** [comment]
Hi Dave,

When you click on the image in my second comment you can see my current version. Everything is running fine, but I really don't want to install program-o every time a new version gets out. So I am just wondering how to update program-o without breaking anything. 

Kind Regards

**Comment by Dave-Morton** [comment]
To upgrade from 2.6.8 to current, you only need to do an overlay install (just copy the new files into the current folder, overwriting the older files). Nothing from 2.6.8 to present requires any changes to the DB.

**Comment by Delilovic** [comment]
Thank you, that is the answer I needed. I was only worried if overwriting files would mess with the files created while using the install script.

**Comment by Dave-Morton** [comment]
The only file created during the install process is the global config file, mentioned earlier, and then only if it doesn't exist, so you're in no danger of the settings kept there if you only do an "overlay install". An `overlay install` doesn't need to have the install script run, so you're safe that way, too. :)

**Comment by Delilovic** [comment]
Perfect explanation, thank you again!

**Comment by Delilovic** [comment]
Should I close the issue or does the admin do this? :D

**Comment by Dave-Morton** [comment]
If you asked the original question, or posted the original issue, and you're satisfied with the outcome of the thread, then you are welcome to close the issue. Or I can (and actually will, in this case). 😄
