### ISSUE TITLE
Error When Trying to Run Bot

### ISSUE THREAD

**Issue by FedgeNo** [Program-O/Program-O#91]
The URL for the API is currently set as:
http://fedgeno.com/program-o/chatbot/conversation_start.php.
Please make sure that you edit this file to change the value of the variable $url in this file to reflect the correct URL address of your chatbot, and to remove this message. 

I looked in that file and there is no variable named $url used anywhere in it at all.

**Comment by Dave-Morton** [comment]
That's because that variable ($url) is set within one of the GUI page scripts, before the script even gets to conversation_start.php. The default GUI is set during the install process, and will be set according to whichever format you selected. these formats (and the script where $url is set) are:

* HTML: gui/plain/index.php
* JSON: gui/jQuery/index.php
* XML: gui/xml/index.php

If you're experiencing trouble with running Program o that is related to the variable $url being incorrect, try looking in the GUI script for the format you selected during the install process. If that does not correct the problem, then perhaps a bit more detail about the specific problem that you're having would be helpful.

**Comment by FedgeNo** [comment]
OK well I'm not sure what I would need to change it to. That file exists.

**Comment by Dave-Morton** [comment]
Is your chatbot installed on a publicly accessible web server? If so, you can post the URL here and I can probably take a look at it and give you some advice as to what needs to be done. Otherwise, you'll need to look at the log files (they're in the logs folder of the Program O installation) and send me the error log's contents, either by posting it here (not really recommended, as it can pose a security risk), or by sending it to me via email.

**Comment by FedgeNo** [comment]
Yeah it's at http://fedgeno.com/program-o/

Sorry for the trouble. I really thought there was just some step I'd missed on setup. I've never run this before.

**Comment by Dave-Morton** [comment]
Not to worry. it happens. The chatbot itself seems to work when you say "test", but so far all other responses are blank. This would indicate to me that you haven't loaded any AIML files yet. You can do se through the admin panel at http://fedgeno.com/program-o/admin/ 
Just log in and navigate to the Upload page to add AIML files to the chatbot. Then you can test it to make sure everything is working.

**Comment by FedgeNo** [comment]
There are a few AIML files. It has some geography Q&A in there and a few other things. Mostly science stuff from ALICE. I just want to get rid of that error message, though.

**Comment by Dave-Morton** [comment]
Most likely, then, you don't yet have a "catchall" category. Something like this might help (modify the response as needed):

    <category>
      <pattern>*</pattern>
      <template>I'm sorry, but I have no response to that.</template>
    </category>

That will handle any input that doesn't have any direct or indirect matches already in the system. As for the error message itself, I don't see it in either the GUI or the error logs, so I'm not quite certain how best to advise you. Or are you referring to the text in the lower-left of the GUI page that mentions something along the lines of, "The URL for the API is currently set as[...]"? If so, you simply need to open the GUI's index page (in your case gui/jquery/index,php) in the text editor of your choice and follow the instructions in the internal documentation.

**Comment by FedgeNo** [comment]
Ooops. Thanks. I saw that line but I assumed there was logic elsewhere in the file to prevent the error message if everything was working. Thanks.

**Comment by NASRAOUI** [comment]
The URL for the API is currently set as:
http://fedgeno.com/program-o/chatbot/conversation_start.php.
Please make sure that you edit this file to change the value of the variable $url in this file to reflect the correct URL address of your chatbot, and to remove this message.

I looked in that file and there is no variable named $url used anywhere in it at all.

**Comment by Program-O** [comment]
Please open a new issue... as this one is closed.... but also fyi look in Program-O/gui/jquery/index.php for the path

**Comment by Dave-Morton** [comment]
@NASRAOUI if you look at the entire content of this issue, you'll see that the variable $URL isn't used in conversation_start.php, but in the GUI's index file (gui/jquery/index.php). I wrote some instructions (here)[https://github.com/Program-O/Program-O/issues/91#issuecomment-180860377] on how to remove that message (which isn't an error message at all, BTW). Please read through that post, and if you have trouble, please open a new issue so that we can take care of it. Thanks. :)

**Comment by NASRAOUI** [comment]
Hi , i can tell me what is the architecture is developped the program o and
why is not developped with MVC

2016-02-09 0:58 GMT+01:00 Dave Morton <notifications@github.com>:

**Comment by Dave-Morton** [comment]
@NASRAOUI 
The biggest reason why we didn't use MVC to develop Program O was because the original code base for the project predates the concept of Model/View/Controller. There is no real "architecture" or framework used, at present, but future versions will probably be based on something along the lines of Laravel or similar (I'm partial to CodeIgniter, but as we all know, that platform has issues, currently). The change over to a new platform will have to wait till I finish my schooling, and have more time to make the changes.

**Comment by SosEquus** [comment]
Hello, i am not sure how to exactly implement it to work with my existent domain... i have to ake widget or frame on my index file that points to conversation_start.php? Thank you

**Comment by patrickschur** [comment]
@SosEquus That's right, you need the `conversation_start.php` for accessing the API. If you need an example, have a look at the files in the `gui` folder.

**Comment by SosEquus** [comment]
Great! you can t imagine how helpfull you were with this reply.
As a newbie, seems that i am on the right path in "thinking", on how should i solve mi own issues.
First i have to try, but with you guy, confidence will increase the way i think. Thanks again. 
P.S, in the future, wouldn t be bad to "integrate" a widget for noobs like many others(botman has that ppolarity, but tottally lacks the way on "creating conversations" as a simple noob, and not a master in php).
Cheers
