### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by wofty** [Program-O/Program-O#94]
Hello, I'm having trouble to installing Program-O and I have this error at the installation.
Parse error: syntax error, unexpected '{' in /mnt/100/sdb/c/0/wofty/install/install_programo.php on line 178

In the file install_programo.php I have this line 178:
try {
$dbConn = new PDO("mysql:host=$dbh;dbname=$dbn;charset=utf8", $dbu, $dbp);
$dbConn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$dbConn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
}
I don't think it's really a Parse error.
Here are my versions: SQL, Apache and PHP :
MySQL
Server: wofty.sql.free.fr via TCP/IP
Server version: 5.0.83
MySQL charset: UTF-8 Unicode (utf8)

Web server
Apache
MySQL client version: 5.1.61
PHP extension: mysql

phpMyAdmin
Version information: 3.1.5

Other question : 
Is it possible to used api.program-o.com with Program-O or it's an other program?

Thanks for your works

**Comment by Program-O** [comment]
Hi there,
Is the PDO extension enabled on your server?

and ....
api.program-o.com is just a demo of program o
basically your version of program o will do the same thing when you set it up

**Comment by wofty** [comment]
I do not know for PDO extension. I'll contact the FREE assistance. I have the possibilty to use PostgreSQL. Is it better than MySQL?
Thanks

**Comment by Dave-Morton** [comment]
Hi, wofty. Let's see what we can do to fix this. First off, let's see if your PHP installation has the PDO extension installed. The easiest way to do this is to create a PHP script that displays some necessary information. In your favorite text editor, create a file with the following contents:

    <?php phpinfo(); ?>

Then save this file as test.php (or some other file name, if you like) and upload it to the same place where you have Program O on your web server. Then point your browser to that uploaded file (example: http:/your.server/path/to/programo/test.php), and look for instances of the "word" PDO. If you cannot find PDO somewhere on the page, then the PDO extension is not installed, and you will have to contact your hosting provider to see about having that extension installed, because Program O will not work without it. If your server's PHP install ~does~ have the PDO extension installed, then we'll have to look elsewhere for the problem.

As for using PostgreSQL with Program O, it's certainly possible to do so, but it would require some changes to the code that sets up the database object that Program O uses internally, and that's a bit tricky to do for some people. PostgreSQL is no better (or worse, really) than MySQL so far as Program O is concerned, so if you would rather use PostgreSQL, I can help you with that, but there's really no advantage to it.

**Comment by wofty** [comment]
Yes, the problem is solved and was with the webhost. PHP version is version 5.0. So I changed the hosting and installation went well. I choose Response Format xml because is faster format. Now I can create a plugin for SARAH with TTS and speech recognition. Thank you again for your work

**Comment by Dave-Morton** [comment]
Glad to have helped.

**Comment by wofty** [comment]
Other question: In Aiml, Is it possible to execute a http request like for exemple : http://192.168.1.7:10/movement?direction=forward
Thanks again
