### ISSUE TITLE
http request in Progam-O and Aiml

### ISSUE THREAD

**Issue by wofty** [Program-O/Program-O#95]
Question: In Aiml, Is it possible to execute a http request like for exemple : 

> <category>

	<pattern>TURN LEFT</pattern>
	<template>http://192.168.1.7:10/movement?direction=left</template>

> </category>

Thanks again

**Comment by Dave-Morton** [comment]
I'm not 100% certain what you mean, wofty. If you want to output the text you've got there, certainly. If, however, you want to have the chatbot *process* the information from a URL like that and output the results, then it's possible, but would require some extra code to accomplish.

**Comment by wofty** [comment]
I don't want to output the text of course but i need to http post a URL. I want to control my robot with Aiml, actually I use XML but I find AIML is better. If I say "robot go forward", I execute http://192.168.1.7:10/movement?direction=left but I don't know how to do that. If you have an example...
Thanks

**Comment by Dave-Morton** [comment]
That's what I thought you meant, but I needed to be sure. This will require "designing" a custom AIML tag, and writing a new function to handle the custom tag. Take a look at the file chatbot\addons\custom_tags\custom_tags.php. In that file are a couple of examples of how to handle custom tags. Basically, you start be figuring out what the new custom AIML tag will be (in your situation, probably <control> would work), then write a function to handle it. Since you want to POST to a specific URL,, but (I think) not have any output from that URL sent to the chatbot's output, there will be a bit of customization involved. You can model the new function after the parse_wiki_tag function and modify it from there, I'm sure. It's at least a good starting point. If you don't feel confident or comfortable with writing such code, please send me an email (my email address is in my profile here), and we can discuss specifics.

**Comment by Program-O** [comment]
:)

**Comment by wofty** [comment]
Hello, I finish to create my plugin. Speech recognition and TTS work well. Now I can start my research to POST to a specific URL. But I found a bug with French langage. I don't find how to make a substitute for this  '. 
I'm explaine, when I say : JE M'APPELLE *  or JE T'EN PRIE
Program-O understand : JE M APPELLE *  or JE T EN PRIE
With Spellcheck Editor we can substitue world but not ', ?,!
I see with the file new.sql in install folder this line : 
(92, 'youa re', 'you are'),
(93, 'youa aare', 'you are'),
I can write this : 
(112, '?', ' ');
But not this : 
(113, ''', ' ');
Do you know if there is a tip for this? 
Thanks a lot

**Comment by wofty** [comment]
Ok I found. I must write like this : 
<pattern>JE M APPELLE *</pattern>
and if Speech recognition recognize JE M'APPELLE or JE M'APPELLE it's ok.

**Comment by Dave-Morton** [comment]
Glad you were able to sort this out. :+1:
