### ISSUE TITLE
CodePracticeAndVulnerabilities

### ISSUE THREAD

**Issue by falconsmilie** [Program-O/Program-O#99]
Hi. 

I am researching AIML with PHP and which packages may be best to use as a base to jump from. 

Your program appears to be one of the few for PHP that has an active team of developers.
_________________________________________________________________________________
However, I´ve had a quick skim through the code and a lot of the practices seem to be outdated :-/ 

Do you have plans for updating to a more excepted approach to programming?
_________________________________________________________________________________
Sadly, i also came across this;

http://www.vulnerability-lab.com/get_content.php?id=1414

I haven´t yet bothered with testing these claims, but on the face of things they appear legit.
_________________________________________________________________________________
Any information you can provide regarding the points i´ve raised would be greatly appreciated.

**Comment by Dave-Morton** [comment]
I was approached by the author of that paper back in late December of 2014, if I remember correctly, letting me know that he was going to publish the paper that you linked to. I have since been able to correct *some* of he issues, but not all (the reasons why are lengthy, so I won't go into them here). the remainder of the issues pointed out in the paper are on the ToDo list, but my available time for this project is still very much limited to only giving occasional support here on GitHub. If you wish to look into the security issues with an eye toward correcting them, you are both welcome and encouraged to do so.

**Comment by Dave-Morton** [comment]
I just had a look at the commit history a moment ago, and I have to point out that my earlier statement about not having addressed **all** of the security issues may be incorrect. There are two different commits from late January (links below) that seem to have addressed the security issues listed above. These commits are:

[25 Jan. 2015](https://github.com/Program-O/Program-O/commit/b823ef1a5789ba3173776dd65971fc470f49b510)
[21 Jan. 2015](https://github.com/Program-O/Program-O/commit/b823ef1a5789ba3173776dd65971fc470f49b510)

Please feel free to review the descriptions in these commits, to determine for yourself whether there may be a problem still or not. :)

**Comment by Program-O** [comment]
Hi all, Yes i remember when we were first told about these, Dave you worked to get the holes fixed. 
:+1:

**Comment by falconsmilie** [comment]
Thank you both for your replies. It's reassuring to know you were onto this ;-)
